{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "gpuType": "T4"
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    },
    "accelerator": "GPU"
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "EyrwRm_WLdeG",
        "outputId": "e90782a7-4681-499a-fcee-67af9323b292"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Cloning into 'GenerativeImage2Text'...\n",
            "remote: Enumerating objects: 160, done.\u001b[K\n",
            "remote: Counting objects: 100% (63/63), done.\u001b[K\n",
            "remote: Compressing objects: 100% (37/37), done.\u001b[K\n",
            "remote: Total 160 (delta 44), reused 33 (delta 26), pack-reused 97\u001b[K\n",
            "Receiving objects: 100% (160/160), 501.71 KiB | 6.19 MiB/s, done.\n",
            "Resolving deltas: 100% (63/63), done.\n",
            "/content/GenerativeImage2Text\n"
          ]
        }
      ],
      "source": [
        "!git clone https://github.com/microsoft/GenerativeImage2Text.git\n",
        "%cd GenerativeImage2Text\n",
        "!pip install -r requirements.txt\n",
        "!python setup.py build develop"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "!python -m generativeimage2text.train -p \"{'type': 'speed_test_forward_backward'}\""
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "pjlZIv1yPIov",
        "outputId": "7b74a012-ffbb-4fa2-8fcc-bcc584ed9706"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "2024-02-25 14:33:33,404.404 14171:train.py:309   <module>(): param:\n",
            "{'type': 'speed_test_forward_backward'}\n",
            "2024-02-25 14:33:35,410.410 14171:train.py:274 speed_test_forward_backward(): SelectTransform(ts=[Compose(\n",
            "    ImageTransform2Dict(image_transform=Compose(\n",
            "    RandomResizedCrop(size=(160, 160), scale=(0.8, 1.0), ratio=(1.0, 1.0), interpolation=bicubic, antialias=warn)\n",
            "    ToTensor()\n",
            "    Normalize(mean=(0.48145466, 0.4578275, 0.40821073), std=(0.26862954, 0.26130258, 0.27577711))\n",
            "))\n",
            "), Compose(\n",
            "    ImageTransform2Dict(image_transform=Compose(\n",
            "    RandomResizedCrop(size=(176, 176), scale=(0.8, 1.0), ratio=(1.0, 1.0), interpolation=bicubic, antialias=warn)\n",
            "    ToTensor()\n",
            "    Normalize(mean=(0.48145466, 0.4578275, 0.40821073), std=(0.26862954, 0.26130258, 0.27577711))\n",
            "))\n",
            "), Compose(\n",
            "    ImageTransform2Dict(image_transform=Compose(\n",
            "    RandomResizedCrop(size=(192, 192), scale=(0.8, 1.0), ratio=(1.0, 1.0), interpolation=bicubic, antialias=warn)\n",
            "    ToTensor()\n",
            "    Normalize(mean=(0.48145466, 0.4578275, 0.40821073), std=(0.26862954, 0.26130258, 0.27577711))\n",
            "))\n",
            "), Compose(\n",
            "    ImageTransform2Dict(image_transform=Compose(\n",
            "    RandomResizedCrop(size=(208, 208), scale=(0.8, 1.0), ratio=(1.0, 1.0), interpolation=bicubic, antialias=warn)\n",
            "    ToTensor()\n",
            "    Normalize(mean=(0.48145466, 0.4578275, 0.40821073), std=(0.26862954, 0.26130258, 0.27577711))\n",
            "))\n",
            "), Compose(\n",
            "    ImageTransform2Dict(image_transform=Compose(\n",
            "    RandomResizedCrop(size=(224, 224), scale=(0.8, 1.0), ratio=(1.0, 1.0), interpolation=bicubic, antialias=warn)\n",
            "    ToTensor()\n",
            "    Normalize(mean=(0.48145466, 0.4578275, 0.40821073), std=(0.26862954, 0.26130258, 0.27577711))\n",
            "))\n",
            ")], selector=<function get_multi_scale_image_transform.<locals>.<lambda> at 0x7ae145cf55a0>)\n",
            "2024-02-25 14:33:41,672.672 14171:decoder.py:657    forward(): : iter=1, avg pos = 2.942926403193269e-05, max loss = 0, min loss = 0\n",
            "2024-02-25 14:33:41,692.692 14171:decoder.py:962 forward_one_ce(): {'num_has_image': 0, 'num_no_image': 0}\n",
            "2024-02-25 14:33:46,886.886 14171:train.py:300 speed_test_forward_backward(): speed = 1553.7233122927328\n",
            "2024-02-25 14:33:51,025.025 14171:train.py:300 speed_test_forward_backward(): speed = 1546.4525239564782\n",
            "2024-02-25 14:33:55,171.171 14171:train.py:300 speed_test_forward_backward(): speed = 1544.0954806026768\n",
            "2024-02-25 14:33:59,339.339 14171:train.py:300 speed_test_forward_backward(): speed = 1535.477814303798\n",
            "2024-02-25 14:34:03,529.529 14171:train.py:300 speed_test_forward_backward(): speed = 1527.62925670109\n",
            "2024-02-25 14:34:07,734.734 14171:train.py:300 speed_test_forward_backward(): speed = 1522.0124061646516\n",
            "2024-02-25 14:34:11,951.951 14171:train.py:300 speed_test_forward_backward(): speed = 1517.7009934822674\n",
            "2024-02-25 14:34:16,192.192 14171:train.py:300 speed_test_forward_backward(): speed = 1509.3198932392806\n",
            "2024-02-25 14:34:20,441.441 14171:train.py:300 speed_test_forward_backward(): speed = 1506.346447590669\n",
            "2024-02-25 14:34:23,777.777 14171:decoder.py:657    forward(): : iter=101, avg pos = 2.9589165933430195e-05, max loss = 10.861443519592285, min loss = -3.262989775976166e-05\n",
            "2024-02-25 14:34:24,693.693 14171:train.py:300 speed_test_forward_backward(): speed = 1505.1135759292583\n",
            "2024-02-25 14:34:28,960.960 14171:train.py:300 speed_test_forward_backward(): speed = 1500.035545699694\n",
            "2024-02-25 14:34:33,238.238 14171:train.py:300 speed_test_forward_backward(): speed = 1496.2243496073988\n",
            "2024-02-25 14:34:37,528.528 14171:train.py:300 speed_test_forward_backward(): speed = 1492.0554428818346\n",
            "2024-02-25 14:34:41,844.844 14171:train.py:300 speed_test_forward_backward(): speed = 1482.6255863509534\n",
            "2024-02-25 14:34:46,166.166 14171:train.py:300 speed_test_forward_backward(): speed = 1481.07623826089\n",
            "2024-02-25 14:34:50,500.500 14171:train.py:300 speed_test_forward_backward(): speed = 1476.7027602387475\n",
            "2024-02-25 14:34:54,869.869 14171:train.py:300 speed_test_forward_backward(): speed = 1465.0084205027372\n",
            "2024-02-25 14:34:59,263.263 14171:train.py:300 speed_test_forward_backward(): speed = 1456.674361131337\n",
            "2024-02-25 14:35:03,681.681 14171:train.py:300 speed_test_forward_backward(): speed = 1448.8614392418383\n",
            "2024-02-25 14:35:07,175.175 14171:decoder.py:657    forward(): : iter=201, avg pos = 2.912459967774339e-05, max loss = 10.874031066894531, min loss = -3.228156128898263e-05\n",
            "2024-02-25 14:35:07,179.179 14171:decoder.py:962 forward_one_ce(): {'num_has_image': 200, 'num_no_image': 0}\n",
            "2024-02-25 14:35:08,137.137 14171:train.py:300 speed_test_forward_backward(): speed = 1436.10239791003\n",
            "2024-02-25 14:35:12,620.620 14171:train.py:300 speed_test_forward_backward(): speed = 1427.8035893240992\n",
            "2024-02-25 14:35:17,130.130 14171:train.py:300 speed_test_forward_backward(): speed = 1419.2794967320172\n",
            "2024-02-25 14:35:21,677.677 14171:train.py:300 speed_test_forward_backward(): speed = 1407.639779071696\n",
            "2024-02-25 14:35:26,229.229 14171:train.py:300 speed_test_forward_backward(): speed = 1405.7716481055827\n",
            "2024-02-25 14:35:30,774.774 14171:train.py:300 speed_test_forward_backward(): speed = 1408.2272205004085\n",
            "2024-02-25 14:35:35,285.285 14171:train.py:300 speed_test_forward_backward(): speed = 1418.856019248648\n",
            "2024-02-25 14:35:39,768.768 14171:train.py:300 speed_test_forward_backward(): speed = 1427.775490364666\n",
            "2024-02-25 14:35:44,237.237 14171:train.py:300 speed_test_forward_backward(): speed = 1432.321049814551\n",
            "2024-02-25 14:35:48,677.677 14171:train.py:300 speed_test_forward_backward(): speed = 1441.4554328254771\n",
            "2024-02-25 14:35:52,214.214 14171:decoder.py:657    forward(): : iter=301, avg pos = 2.920469705713913e-05, max loss = 10.88432788848877, min loss = -3.238415956730023e-05\n",
            "2024-02-25 14:35:53,240.240 14171:train.py:300 speed_test_forward_backward(): speed = 1402.6342527473291\n",
            "2024-02-25 14:35:57,679.679 14171:train.py:300 speed_test_forward_backward(): speed = 1441.8217234927567\n",
            "2024-02-25 14:36:02,109.109 14171:train.py:300 speed_test_forward_backward(): speed = 1445.063099303689\n",
            "2024-02-25 14:36:06,527.527 14171:train.py:300 speed_test_forward_backward(): speed = 1448.728665646718\n",
            "2024-02-25 14:36:10,945.945 14171:train.py:300 speed_test_forward_backward(): speed = 1448.4883588539028\n",
            "2024-02-25 14:36:15,359.359 14171:train.py:300 speed_test_forward_backward(): speed = 1450.1277634749936\n",
            "2024-02-25 14:36:19,790.790 14171:train.py:300 speed_test_forward_backward(): speed = 1444.73776952049\n",
            "2024-02-25 14:36:24,233.233 14171:train.py:300 speed_test_forward_backward(): speed = 1440.5090185204385\n",
            "2024-02-25 14:36:28,675.675 14171:train.py:300 speed_test_forward_backward(): speed = 1440.6903924117632\n",
            "2024-02-25 14:36:33,122.122 14171:train.py:300 speed_test_forward_backward(): speed = 1439.4719830435008\n",
            "2024-02-25 14:36:36,615.615 14171:decoder.py:657    forward(): : iter=401, avg pos = 2.9502296456485055e-05, max loss = 10.800057411193848, min loss = -3.2553500204812735e-05\n",
            "2024-02-25 14:36:36,619.619 14171:decoder.py:962 forward_one_ce(): {'num_has_image': 400, 'num_no_image': 0}\n",
            "2024-02-25 14:36:37,576.576 14171:train.py:300 speed_test_forward_backward(): speed = 1436.9477949913353\n",
            "2024-02-25 14:36:42,042.042 14171:train.py:300 speed_test_forward_backward(): speed = 1433.0290274968568\n",
            "2024-02-25 14:36:46,503.503 14171:train.py:300 speed_test_forward_backward(): speed = 1434.9576219542182\n",
            "2024-02-25 14:36:50,976.976 14171:train.py:300 speed_test_forward_backward(): speed = 1430.7527505040287\n",
            "2024-02-25 14:36:55,454.454 14171:train.py:300 speed_test_forward_backward(): speed = 1429.4429114694233\n",
            "2024-02-25 14:36:59,913.913 14171:train.py:300 speed_test_forward_backward(): speed = 1435.209420402753\n",
            "2024-02-25 14:37:04,374.374 14171:train.py:300 speed_test_forward_backward(): speed = 1434.76495838876\n",
            "2024-02-25 14:37:08,834.834 14171:train.py:300 speed_test_forward_backward(): speed = 1435.3391134283584\n",
            "2024-02-25 14:37:13,286.286 14171:train.py:300 speed_test_forward_backward(): speed = 1437.4405628025274\n",
            "2024-02-25 14:37:17,736.736 14171:train.py:300 speed_test_forward_backward(): speed = 1438.2901567507765\n",
            "2024-02-25 14:37:21,224.224 14171:decoder.py:657    forward(): : iter=501, avg pos = 2.9324848583200946e-05, max loss = 10.852662086486816, min loss = -3.22253727063071e-05\n",
            "2024-02-25 14:37:22,184.184 14171:train.py:300 speed_test_forward_backward(): speed = 1439.0617527376223\n",
            "2024-02-25 14:37:26,632.632 14171:train.py:300 speed_test_forward_backward(): speed = 1438.8038965638784\n",
            "2024-02-25 14:37:31,165.165 14171:train.py:300 speed_test_forward_backward(): speed = 1412.057164980558\n",
            "2024-02-25 14:37:35,572.572 14171:train.py:300 speed_test_forward_backward(): speed = 1452.3977087610865\n",
            "2024-02-25 14:37:40,023.023 14171:train.py:300 speed_test_forward_backward(): speed = 1437.8748231752022\n",
            "2024-02-25 14:37:44,473.473 14171:train.py:300 speed_test_forward_backward(): speed = 1438.5311771434513\n",
            "2024-02-25 14:37:48,925.925 14171:train.py:300 speed_test_forward_backward(): speed = 1437.5086103907113\n",
            "2024-02-25 14:37:53,380.380 14171:train.py:300 speed_test_forward_backward(): speed = 1436.5787483143567\n",
            "2024-02-25 14:37:57,835.835 14171:train.py:300 speed_test_forward_backward(): speed = 1436.8655716813432\n",
            "2024-02-25 14:38:02,288.288 14171:train.py:300 speed_test_forward_backward(): speed = 1437.3061030857841\n",
            "2024-02-25 14:38:05,784.784 14171:decoder.py:657    forward(): : iter=601, avg pos = 2.9187811378506012e-05, max loss = 10.867059707641602, min loss = -3.214101161574945e-05\n",
            "2024-02-25 14:38:05,788.788 14171:decoder.py:962 forward_one_ce(): {'num_has_image': 600, 'num_no_image': 0}\n",
            "2024-02-25 14:38:06,742.742 14171:train.py:300 speed_test_forward_backward(): speed = 1437.121733295372\n",
            "2024-02-25 14:38:11,192.192 14171:train.py:300 speed_test_forward_backward(): speed = 1438.0752565813655\n",
            "2024-02-25 14:38:15,647.647 14171:train.py:300 speed_test_forward_backward(): speed = 1436.6928487729406\n",
            "2024-02-25 14:38:20,096.096 14171:train.py:300 speed_test_forward_backward(): speed = 1438.6590039073942\n",
            "2024-02-25 14:38:24,545.545 14171:train.py:300 speed_test_forward_backward(): speed = 1438.5909244619797\n",
            "2024-02-25 14:38:28,999.999 14171:train.py:300 speed_test_forward_backward(): speed = 1436.8563423368719\n",
            "2024-02-25 14:38:33,452.452 14171:train.py:300 speed_test_forward_backward(): speed = 1437.4758174229153\n",
            "2024-02-25 14:38:37,904.904 14171:train.py:300 speed_test_forward_backward(): speed = 1437.7473667364413\n",
            "2024-02-25 14:38:42,354.354 14171:train.py:300 speed_test_forward_backward(): speed = 1438.1969920686197\n",
            "2024-02-25 14:38:46,807.807 14171:train.py:300 speed_test_forward_backward(): speed = 1437.4742778837326\n",
            "2024-02-25 14:38:50,301.301 14171:decoder.py:657    forward(): : iter=701, avg pos = 2.955929267045576e-05, max loss = 10.780726432800293, min loss = -3.2176794775296e-05\n",
            "2024-02-25 14:38:51,263.263 14171:train.py:300 speed_test_forward_backward(): speed = 1436.295805109488\n",
            "2024-02-25 14:38:55,718.718 14171:train.py:300 speed_test_forward_backward(): speed = 1436.599814015937\n",
            "2024-02-25 14:39:00,173.173 14171:train.py:300 speed_test_forward_backward(): speed = 1436.503870128091\n",
            "2024-02-25 14:39:04,633.633 14171:train.py:300 speed_test_forward_backward(): speed = 1435.0488330621945\n",
            "2024-02-25 14:39:09,094.094 14171:train.py:300 speed_test_forward_backward(): speed = 1434.9742676918072\n",
            "2024-02-25 14:39:13,547.547 14171:train.py:300 speed_test_forward_backward(): speed = 1437.3394270474441\n",
            "2024-02-25 14:39:18,000.000 14171:train.py:300 speed_test_forward_backward(): speed = 1437.2263781228642\n",
            "2024-02-25 14:39:22,450.450 14171:train.py:300 speed_test_forward_backward(): speed = 1438.4430685418686\n",
            "2024-02-25 14:39:26,897.897 14171:train.py:300 speed_test_forward_backward(): speed = 1439.1352775748862\n",
            "2024-02-25 14:39:31,347.347 14171:train.py:300 speed_test_forward_backward(): speed = 1438.2452296776244\n",
            "2024-02-25 14:39:34,840.840 14171:decoder.py:657    forward(): : iter=801, avg pos = 2.9375109079410322e-05, max loss = 10.797149658203125, min loss = -3.232354356441647e-05\n",
            "2024-02-25 14:39:34,844.844 14171:decoder.py:962 forward_one_ce(): {'num_has_image': 800, 'num_no_image': 0}\n",
            "2024-02-25 14:39:35,799.799 14171:train.py:300 speed_test_forward_backward(): speed = 1437.6352545579712\n",
            "2024-02-25 14:39:40,248.248 14171:train.py:300 speed_test_forward_backward(): speed = 1438.6370296562327\n",
            "2024-02-25 14:39:44,701.701 14171:train.py:300 speed_test_forward_backward(): speed = 1437.4799741951804\n",
            "2024-02-25 14:39:49,148.148 14171:train.py:300 speed_test_forward_backward(): speed = 1439.2095043907784\n",
            "2024-02-25 14:39:53,599.599 14171:train.py:300 speed_test_forward_backward(): speed = 1437.8309232403078\n",
            "2024-02-25 14:39:58,046.046 14171:train.py:300 speed_test_forward_backward(): speed = 1439.5023969321842\n",
            "2024-02-25 14:40:02,496.496 14171:train.py:300 speed_test_forward_backward(): speed = 1438.4103870806227\n",
            "2024-02-25 14:40:06,946.946 14171:train.py:300 speed_test_forward_backward(): speed = 1438.233285559291\n",
            "2024-02-25 14:40:11,397.397 14171:train.py:300 speed_test_forward_backward(): speed = 1437.8738219187444\n",
            "2024-02-25 14:40:15,847.847 14171:train.py:300 speed_test_forward_backward(): speed = 1438.188516145686\n",
            "2024-02-25 14:40:19,344.344 14171:decoder.py:657    forward(): : iter=901, avg pos = 2.9188659027568065e-05, max loss = 10.84465503692627, min loss = -3.259961522417143e-05\n",
            "2024-02-25 14:40:20,304.304 14171:train.py:300 speed_test_forward_backward(): speed = 1436.3152486032823\n",
            "2024-02-25 14:40:24,752.752 14171:train.py:300 speed_test_forward_backward(): speed = 1438.698019494999\n",
            "2024-02-25 14:40:29,207.207 14171:train.py:300 speed_test_forward_backward(): speed = 1436.8185032641018\n",
            "2024-02-25 14:40:33,659.659 14171:train.py:300 speed_test_forward_backward(): speed = 1437.6616640256782\n",
            "2024-02-25 14:40:38,109.109 14171:train.py:300 speed_test_forward_backward(): speed = 1438.1106964320547\n",
            "2024-02-25 14:40:42,561.561 14171:train.py:300 speed_test_forward_backward(): speed = 1437.7817122896745\n",
            "2024-02-25 14:40:47,010.010 14171:train.py:300 speed_test_forward_backward(): speed = 1438.5544587341867\n",
            "2024-02-25 14:40:51,458.458 14171:train.py:300 speed_test_forward_backward(): speed = 1439.0066718955106\n",
            "2024-02-25 14:40:55,906.906 14171:train.py:300 speed_test_forward_backward(): speed = 1438.825721669557\n",
            "2024-02-25 14:41:00,357.357 14171:train.py:300 speed_test_forward_backward(): speed = 1438.1874373990247\n",
            "2024-02-25 14:41:03,850.850 14171:decoder.py:657    forward(): : iter=1001, avg pos = 2.9237902708700858e-05, max loss = 10.799030303955078, min loss = -3.2214506063610315e-05\n",
            "2024-02-25 14:41:03,854.854 14171:decoder.py:962 forward_one_ce(): {'num_has_image': 1000, 'num_no_image': 0}\n",
            "2024-02-25 14:41:04,811.811 14171:train.py:300 speed_test_forward_backward(): speed = 1436.7589799759166\n",
            "2024-02-25 14:41:09,261.261 14171:train.py:300 speed_test_forward_backward(): speed = 1438.4859266709152\n",
            "2024-02-25 14:41:13,710.710 14171:train.py:300 speed_test_forward_backward(): speed = 1438.7669573460335\n",
            "2024-02-25 14:41:18,167.167 14171:train.py:300 speed_test_forward_backward(): speed = 1435.804743295814\n",
            "2024-02-25 14:41:22,621.621 14171:train.py:300 speed_test_forward_backward(): speed = 1437.1047299502054\n",
            "2024-02-25 14:41:27,077.077 14171:train.py:300 speed_test_forward_backward(): speed = 1436.2295628494562\n",
            "2024-02-25 14:41:31,524.524 14171:train.py:300 speed_test_forward_backward(): speed = 1439.3083567677083\n",
            "2024-02-25 14:41:35,974.974 14171:train.py:300 speed_test_forward_backward(): speed = 1438.2607187974813\n",
            "2024-02-25 14:41:40,423.423 14171:train.py:300 speed_test_forward_backward(): speed = 1438.651139361425\n",
            "2024-02-25 14:41:44,875.875 14171:train.py:300 speed_test_forward_backward(): speed = 1437.809359341819\n",
            "2024-02-25 14:41:48,365.365 14171:decoder.py:657    forward(): : iter=1101, avg pos = 2.938502439064905e-05, max loss = 10.963743209838867, min loss = -3.2248481147689745e-05\n",
            "2024-02-25 14:41:49,323.323 14171:train.py:300 speed_test_forward_backward(): speed = 1438.913260107111\n",
            "2024-02-25 14:41:53,774.774 14171:train.py:300 speed_test_forward_backward(): speed = 1437.8236068451074\n",
            "2024-02-25 14:41:58,221.221 14171:train.py:300 speed_test_forward_backward(): speed = 1439.4272908537444\n",
            "2024-02-25 14:42:02,672.672 14171:train.py:300 speed_test_forward_backward(): speed = 1438.0508349182483\n",
            "2024-02-25 14:42:07,125.125 14171:train.py:300 speed_test_forward_backward(): speed = 1437.154433166985\n",
            "2024-02-25 14:42:11,574.574 14171:train.py:300 speed_test_forward_backward(): speed = 1438.5540732712514\n",
            "2024-02-25 14:42:16,026.026 14171:train.py:300 speed_test_forward_backward(): speed = 1437.6661298624815\n",
            "2024-02-25 14:42:20,482.482 14171:train.py:300 speed_test_forward_backward(): speed = 1436.595816098066\n",
            "2024-02-25 14:42:24,933.933 14171:train.py:300 speed_test_forward_backward(): speed = 1437.7424383611858\n",
            "2024-02-25 14:42:29,390.390 14171:train.py:300 speed_test_forward_backward(): speed = 1436.2732113550544\n",
            "2024-02-25 14:42:32,884.884 14171:decoder.py:657    forward(): : iter=1201, avg pos = 2.8957114409422502e-05, max loss = 10.779483795166016, min loss = -3.193678639945574e-05\n",
            "2024-02-25 14:42:32,888.888 14171:decoder.py:962 forward_one_ce(): {'num_has_image': 1200, 'num_no_image': 0}\n",
            "2024-02-25 14:42:33,845.845 14171:train.py:300 speed_test_forward_backward(): speed = 1436.7983540019773\n",
            "2024-02-25 14:42:38,297.297 14171:train.py:300 speed_test_forward_backward(): speed = 1437.6166992149583\n",
            "2024-02-25 14:42:42,751.751 14171:train.py:300 speed_test_forward_backward(): speed = 1437.0420287839402\n",
            "2024-02-25 14:42:47,199.199 14171:train.py:300 speed_test_forward_backward(): speed = 1438.7041881610821\n",
            "2024-02-25 14:42:51,650.650 14171:train.py:300 speed_test_forward_backward(): speed = 1438.064162726218\n",
            "2024-02-25 14:42:56,106.106 14171:train.py:300 speed_test_forward_backward(): speed = 1436.458516501305\n",
            "2024-02-25 14:43:00,556.556 14171:train.py:300 speed_test_forward_backward(): speed = 1438.1813502160524\n",
            "2024-02-25 14:43:05,005.005 14171:train.py:300 speed_test_forward_backward(): speed = 1438.5243161561705\n",
            "2024-02-25 14:43:09,462.462 14171:train.py:300 speed_test_forward_backward(): speed = 1436.3203209056312\n",
            "2024-02-25 14:43:13,915.915 14171:train.py:300 speed_test_forward_backward(): speed = 1437.218452282699\n",
            "2024-02-25 14:43:17,429.429 14171:decoder.py:657    forward(): : iter=1301, avg pos = 2.983289596159011e-05, max loss = 10.837618827819824, min loss = -3.228105924790725e-05\n",
            "2024-02-25 14:43:18,399.399 14171:train.py:300 speed_test_forward_backward(): speed = 1427.5451206076411\n",
            "2024-02-25 14:43:22,874.874 14171:train.py:300 speed_test_forward_backward(): speed = 1430.1846202255845\n",
            "2024-02-25 14:43:27,326.326 14171:train.py:300 speed_test_forward_backward(): speed = 1437.9774978746564\n",
            "2024-02-25 14:43:31,798.798 14171:train.py:300 speed_test_forward_backward(): speed = 1431.0723457594142\n",
            "2024-02-25 14:43:36,245.245 14171:train.py:300 speed_test_forward_backward(): speed = 1439.5351280349385\n",
            "2024-02-25 14:43:40,700.700 14171:train.py:300 speed_test_forward_backward(): speed = 1436.4851133656596\n",
            "2024-02-25 14:43:45,154.154 14171:train.py:300 speed_test_forward_backward(): speed = 1437.0119495529818\n",
            "2024-02-25 14:43:49,601.601 14171:train.py:300 speed_test_forward_backward(): speed = 1439.287288729113\n",
            "2024-02-25 14:43:54,048.048 14171:train.py:300 speed_test_forward_backward(): speed = 1439.2588131296898\n",
            "2024-02-25 14:43:58,511.511 14171:train.py:300 speed_test_forward_backward(): speed = 1434.2291932131877\n",
            "2024-02-25 14:44:02,002.002 14171:decoder.py:657    forward(): : iter=1401, avg pos = 2.9473849281203002e-05, max loss = 10.811186790466309, min loss = -3.220965663786046e-05\n",
            "2024-02-25 14:44:02,006.006 14171:decoder.py:962 forward_one_ce(): {'num_has_image': 1400, 'num_no_image': 0}\n",
            "2024-02-25 14:44:02,964.964 14171:train.py:300 speed_test_forward_backward(): speed = 1437.362824008478\n",
            "2024-02-25 14:44:07,423.423 14171:train.py:300 speed_test_forward_backward(): speed = 1435.4990748564155\n",
            "2024-02-25 14:44:11,874.874 14171:train.py:300 speed_test_forward_backward(): speed = 1437.8263023504658\n",
            "2024-02-25 14:44:16,327.327 14171:train.py:300 speed_test_forward_backward(): speed = 1437.4268616918025\n",
            "2024-02-25 14:44:20,777.777 14171:train.py:300 speed_test_forward_backward(): speed = 1438.3784778414483\n",
            "2024-02-25 14:44:25,228.228 14171:train.py:300 speed_test_forward_backward(): speed = 1437.817137673482\n",
            "2024-02-25 14:44:29,672.672 14171:train.py:300 speed_test_forward_backward(): speed = 1440.314088650032\n",
            "2024-02-25 14:44:34,127.127 14171:train.py:300 speed_test_forward_backward(): speed = 1436.6618614783836\n",
            "2024-02-25 14:44:38,581.581 14171:train.py:300 speed_test_forward_backward(): speed = 1436.918796547825\n",
            "2024-02-25 14:44:43,035.035 14171:train.py:300 speed_test_forward_backward(): speed = 1437.1388909248046\n",
            "2024-02-25 14:44:46,528.528 14171:decoder.py:657    forward(): : iter=1501, avg pos = 2.9197806725278497e-05, max loss = 10.774587631225586, min loss = -3.276060306234285e-05\n",
            "2024-02-25 14:44:47,491.491 14171:train.py:300 speed_test_forward_backward(): speed = 1436.3247784130278\n",
            "2024-02-25 14:44:51,940.940 14171:train.py:300 speed_test_forward_backward(): speed = 1438.6646325077897\n",
            "2024-02-25 14:44:56,396.396 14171:train.py:300 speed_test_forward_backward(): speed = 1436.502870780034\n",
            "2024-02-25 14:45:00,844.844 14171:train.py:300 speed_test_forward_backward(): speed = 1438.7465991724227\n",
            "2024-02-25 14:45:05,296.296 14171:train.py:300 speed_test_forward_backward(): speed = 1437.7194140556858\n",
            "2024-02-25 14:45:09,750.750 14171:train.py:300 speed_test_forward_backward(): speed = 1437.0322586654743\n",
            "2024-02-25 14:45:14,200.200 14171:train.py:300 speed_test_forward_backward(): speed = 1438.2983256110915\n",
            "2024-02-25 14:45:18,656.656 14171:train.py:300 speed_test_forward_backward(): speed = 1436.2546143082252\n",
            "2024-02-25 14:45:23,109.109 14171:train.py:300 speed_test_forward_backward(): speed = 1437.411544467125\n",
            "2024-02-25 14:45:27,558.558 14171:train.py:300 speed_test_forward_backward(): speed = 1438.6940098904115\n",
            "2024-02-25 14:45:31,047.047 14171:decoder.py:657    forward(): : iter=1601, avg pos = 2.883700653910637e-05, max loss = 10.789599418640137, min loss = -3.255191768403165e-05\n",
            "2024-02-25 14:45:31,051.051 14171:decoder.py:962 forward_one_ce(): {'num_has_image': 1600, 'num_no_image': 0}\n",
            "2024-02-25 14:45:32,005.005 14171:train.py:300 speed_test_forward_backward(): speed = 1439.1126715522485\n",
            "2024-02-25 14:45:36,456.456 14171:train.py:300 speed_test_forward_backward(): speed = 1438.0791856961093\n",
            "2024-02-25 14:45:40,905.905 14171:train.py:300 speed_test_forward_backward(): speed = 1438.500264672667\n",
            "2024-02-25 14:45:45,360.360 14171:train.py:300 speed_test_forward_backward(): speed = 1436.6597085646524\n",
            "2024-02-25 14:45:49,815.815 14171:train.py:300 speed_test_forward_backward(): speed = 1436.7450611587724\n",
            "2024-02-25 14:45:54,270.270 14171:train.py:300 speed_test_forward_backward(): speed = 1436.8009687598085\n",
            "2024-02-25 14:45:58,721.721 14171:train.py:300 speed_test_forward_backward(): speed = 1438.0172468564135\n",
            "2024-02-25 14:46:03,170.170 14171:train.py:300 speed_test_forward_backward(): speed = 1438.5276310070224\n",
            "2024-02-25 14:46:07,626.626 14171:train.py:300 speed_test_forward_backward(): speed = 1436.431228834635\n",
            "2024-02-25 14:46:12,075.075 14171:train.py:300 speed_test_forward_backward(): speed = 1438.676044051973\n",
            "2024-02-25 14:46:15,565.565 14171:decoder.py:657    forward(): : iter=1701, avg pos = 2.8802412998629734e-05, max loss = 10.843949317932129, min loss = -3.31400333379861e-05\n",
            "2024-02-25 14:46:16,526.526 14171:train.py:300 speed_test_forward_backward(): speed = 1437.8799835190582\n",
            "2024-02-25 14:46:20,986.986 14171:train.py:300 speed_test_forward_backward(): speed = 1435.2933728575033\n",
            "2024-02-25 14:46:25,438.438 14171:train.py:300 speed_test_forward_backward(): speed = 1437.727345422145\n",
            "2024-02-25 14:46:29,888.888 14171:train.py:300 speed_test_forward_backward(): speed = 1438.1701006211067\n",
            "2024-02-25 14:46:34,345.345 14171:train.py:300 speed_test_forward_backward(): speed = 1436.1920641394415\n",
            "2024-02-25 14:46:38,797.797 14171:train.py:300 speed_test_forward_backward(): speed = 1437.3604380992851\n",
            "2024-02-25 14:46:43,244.244 14171:train.py:300 speed_test_forward_backward(): speed = 1439.2693852397006\n",
            "2024-02-25 14:46:47,692.692 14171:train.py:300 speed_test_forward_backward(): speed = 1439.1189980808742\n",
            "2024-02-25 14:46:52,143.143 14171:train.py:300 speed_test_forward_backward(): speed = 1437.9684082999458\n",
            "2024-02-25 14:46:56,592.592 14171:train.py:300 speed_test_forward_backward(): speed = 1438.5768930328913\n",
            "2024-02-25 14:47:00,091.091 14171:decoder.py:657    forward(): : iter=1801, avg pos = 2.8937058232259005e-05, max loss = 10.868714332580566, min loss = -3.244683102821e-05\n",
            "2024-02-25 14:47:00,094.094 14171:decoder.py:962 forward_one_ce(): {'num_has_image': 1800, 'num_no_image': 0}\n",
            "2024-02-25 14:47:01,050.050 14171:train.py:300 speed_test_forward_backward(): speed = 1435.6973106908204\n",
            "2024-02-25 14:47:05,506.506 14171:train.py:300 speed_test_forward_backward(): speed = 1436.381114468467\n",
            "2024-02-25 14:47:09,962.962 14171:train.py:300 speed_test_forward_backward(): speed = 1436.3429161422441\n",
            "2024-02-25 14:47:14,420.420 14171:train.py:300 speed_test_forward_backward(): speed = 1435.949138381162\n",
            "2024-02-25 14:47:18,876.876 14171:train.py:300 speed_test_forward_backward(): speed = 1436.1874537774847\n",
            "2024-02-25 14:47:23,324.324 14171:train.py:300 speed_test_forward_backward(): speed = 1438.948201329865\n",
            "2024-02-25 14:47:27,775.775 14171:train.py:300 speed_test_forward_backward(): speed = 1438.1880538254902\n",
            "2024-02-25 14:47:32,229.229 14171:train.py:300 speed_test_forward_backward(): speed = 1437.0091032459588\n",
            "2024-02-25 14:47:36,683.683 14171:train.py:300 speed_test_forward_backward(): speed = 1437.0435673973814\n",
            "2024-02-25 14:47:41,137.137 14171:train.py:300 speed_test_forward_backward(): speed = 1436.9540255788997\n",
            "2024-02-25 14:47:44,630.630 14171:decoder.py:657    forward(): : iter=1901, avg pos = 2.9172191716497764e-05, max loss = 10.833545684814453, min loss = -3.258409196860157e-05\n",
            "2024-02-25 14:47:45,587.587 14171:train.py:300 speed_test_forward_backward(): speed = 1438.299712785267\n",
            "2024-02-25 14:47:50,035.035 14171:train.py:300 speed_test_forward_backward(): speed = 1438.8138450281638\n",
            "2024-02-25 14:47:54,487.487 14171:train.py:300 speed_test_forward_backward(): speed = 1437.8740529778033\n",
            "2024-02-25 14:47:58,941.941 14171:train.py:300 speed_test_forward_backward(): speed = 1436.9802561758836\n",
            "2024-02-25 14:48:03,393.393 14171:train.py:300 speed_test_forward_backward(): speed = 1437.7301175708656\n",
            "2024-02-25 14:48:07,844.844 14171:train.py:300 speed_test_forward_backward(): speed = 1437.7151018931681\n",
            "2024-02-25 14:48:12,298.298 14171:train.py:300 speed_test_forward_backward(): speed = 1437.1138855476063\n",
            "2024-02-25 14:48:16,746.746 14171:train.py:300 speed_test_forward_backward(): speed = 1438.9276837616105\n",
            "2024-02-25 14:48:21,200.200 14171:train.py:300 speed_test_forward_backward(): speed = 1437.0473370142367\n",
            "2024-02-25 14:48:25,660.660 14171:train.py:300 speed_test_forward_backward(): speed = 1435.1323830989397\n",
            "2024-02-25 14:48:29,154.154 14171:decoder.py:657    forward(): : iter=2001, avg pos = 2.9594033549074084e-05, max loss = 10.8194580078125, min loss = -3.19663122354541e-05\n",
            "2024-02-25 14:48:29,157.157 14171:decoder.py:962 forward_one_ce(): {'num_has_image': 2000, 'num_no_image': 0}\n",
            "2024-02-25 14:48:30,111.111 14171:train.py:300 speed_test_forward_backward(): speed = 1437.9697948378132\n",
            "2024-02-25 14:48:34,559.559 14171:train.py:300 speed_test_forward_backward(): speed = 1438.958614605259\n",
            "2024-02-25 14:48:39,012.012 14171:train.py:300 speed_test_forward_backward(): speed = 1437.3362715945439\n",
            "2024-02-25 14:48:43,469.469 14171:train.py:300 speed_test_forward_backward(): speed = 1436.077582242967\n",
            "2024-02-25 14:48:47,919.919 14171:train.py:300 speed_test_forward_backward(): speed = 1438.420253025642\n",
            "2024-02-25 14:48:52,371.371 14171:train.py:300 speed_test_forward_backward(): speed = 1437.5879817238367\n",
            "2024-02-25 14:48:56,828.828 14171:train.py:300 speed_test_forward_backward(): speed = 1436.1184555633813\n",
            "2024-02-25 14:49:01,279.279 14171:train.py:300 speed_test_forward_backward(): speed = 1437.7484448230325\n",
            "2024-02-25 14:49:05,732.732 14171:train.py:300 speed_test_forward_backward(): speed = 1437.481975612623\n",
            "2024-02-25 14:49:10,184.184 14171:train.py:300 speed_test_forward_backward(): speed = 1437.7559144673933\n",
            "2024-02-25 14:49:13,680.680 14171:decoder.py:657    forward(): : iter=2101, avg pos = 2.9262699172249995e-05, max loss = 10.777565956115723, min loss = -3.2328713132301345e-05\n",
            "2024-02-25 14:49:14,639.639 14171:train.py:300 speed_test_forward_backward(): speed = 1436.5602971124993\n",
            "2024-02-25 14:49:19,095.095 14171:train.py:300 speed_test_forward_backward(): speed = 1436.2939606947257\n",
            "2024-02-25 14:49:23,547.547 14171:train.py:300 speed_test_forward_backward(): speed = 1437.821604476241\n",
            "2024-02-25 14:49:28,004.004 14171:train.py:300 speed_test_forward_backward(): speed = 1436.1909115461774\n",
            "2024-02-25 14:49:32,460.460 14171:train.py:300 speed_test_forward_backward(): speed = 1436.2267196409523\n",
            "2024-02-25 14:49:36,907.907 14171:train.py:300 speed_test_forward_backward(): speed = 1439.3441661311394\n",
            "2024-02-25 14:49:41,358.358 14171:train.py:300 speed_test_forward_backward(): speed = 1438.175263084608\n",
            "2024-02-25 14:49:45,813.813 14171:train.py:300 speed_test_forward_backward(): speed = 1436.5572219582698\n",
            "2024-02-25 14:49:50,263.263 14171:train.py:300 speed_test_forward_backward(): speed = 1438.4768306674475\n",
            "2024-02-25 14:49:54,710.710 14171:train.py:300 speed_test_forward_backward(): speed = 1439.001734883083\n",
            "2024-02-25 14:49:58,200.200 14171:decoder.py:657    forward(): : iter=2201, avg pos = 2.9617611289722845e-05, max loss = 10.927732467651367, min loss = -3.232474409742281e-05\n",
            "2024-02-25 14:49:58,204.204 14171:decoder.py:962 forward_one_ce(): {'num_has_image': 2200, 'num_no_image': 0}\n",
            "2024-02-25 14:49:59,159.159 14171:train.py:300 speed_test_forward_backward(): speed = 1438.7184534040064\n",
            "2024-02-25 14:50:03,606.606 14171:train.py:300 speed_test_forward_backward(): speed = 1439.2807292093094\n",
            "2024-02-25 14:50:08,053.053 14171:train.py:300 speed_test_forward_backward(): speed = 1439.390628348829\n",
            "2024-02-25 14:50:12,508.508 14171:train.py:300 speed_test_forward_backward(): speed = 1436.8783391366487\n",
            "2024-02-25 14:50:16,959.959 14171:train.py:300 speed_test_forward_backward(): speed = 1437.9107923127572\n",
            "2024-02-25 14:50:21,409.409 14171:train.py:300 speed_test_forward_backward(): speed = 1438.13527422378\n",
            "2024-02-25 14:50:25,865.865 14171:train.py:300 speed_test_forward_backward(): speed = 1436.2844312939164\n",
            "2024-02-25 14:50:30,317.317 14171:train.py:300 speed_test_forward_backward(): speed = 1437.6651288966477\n",
            "2024-02-25 14:50:34,765.765 14171:train.py:300 speed_test_forward_backward(): speed = 1439.027500289617\n",
            "2024-02-25 14:50:39,217.217 14171:train.py:300 speed_test_forward_backward(): speed = 1437.6409521453047\n",
            "2024-02-25 14:50:42,710.710 14171:decoder.py:657    forward(): : iter=2301, avg pos = 2.9230404834379442e-05, max loss = 10.833394050598145, min loss = -3.218782876501791e-05\n",
            "2024-02-25 14:50:43,671.671 14171:train.py:300 speed_test_forward_backward(): speed = 1437.0005643925424\n",
            "2024-02-25 14:50:48,121.121 14171:train.py:300 speed_test_forward_backward(): speed = 1438.3179004275376\n",
            "2024-02-25 14:50:52,572.572 14171:train.py:300 speed_test_forward_backward(): speed = 1438.0129329071292\n",
            "2024-02-25 14:50:57,021.021 14171:train.py:300 speed_test_forward_backward(): speed = 1438.6303989614075\n",
            "2024-02-25 14:51:01,470.470 14171:train.py:300 speed_test_forward_backward(): speed = 1438.6206843328532\n",
            "2024-02-25 14:51:05,920.920 14171:train.py:300 speed_test_forward_backward(): speed = 1438.3275338989758\n",
            "2024-02-25 14:51:10,372.372 14171:train.py:300 speed_test_forward_backward(): speed = 1437.724188265789\n",
            "2024-02-25 14:51:14,821.821 14171:train.py:300 speed_test_forward_backward(): speed = 1438.6856823215262\n",
            "2024-02-25 14:51:19,270.270 14171:train.py:300 speed_test_forward_backward(): speed = 1438.511519433417\n",
            "2024-02-25 14:51:23,721.721 14171:train.py:300 speed_test_forward_backward(): speed = 1438.1658628056334\n",
            "2024-02-25 14:51:27,214.214 14171:decoder.py:657    forward(): : iter=2401, avg pos = 2.900514482462313e-05, max loss = 10.812522888183594, min loss = -3.233919051126577e-05\n",
            "2024-02-25 14:51:27,217.217 14171:decoder.py:962 forward_one_ce(): {'num_has_image': 2400, 'num_no_image': 0}\n",
            "2024-02-25 14:51:28,173.173 14171:train.py:300 speed_test_forward_backward(): speed = 1437.488518747001\n",
            "2024-02-25 14:51:32,625.625 14171:train.py:300 speed_test_forward_backward(): speed = 1437.851332525729\n",
            "2024-02-25 14:51:37,076.076 14171:train.py:300 speed_test_forward_backward(): speed = 1437.8986226814939\n",
            "2024-02-25 14:51:41,532.532 14171:train.py:300 speed_test_forward_backward(): speed = 1436.455057443924\n",
            "2024-02-25 14:51:45,982.982 14171:train.py:300 speed_test_forward_backward(): speed = 1438.3425623720987\n",
            "2024-02-25 14:51:50,434.434 14171:train.py:300 speed_test_forward_backward(): speed = 1437.4793583755502\n",
            "2024-02-25 14:51:54,880.880 14171:train.py:300 speed_test_forward_backward(): speed = 1439.7279938565416\n",
            "2024-02-25 14:51:59,328.328 14171:train.py:300 speed_test_forward_backward(): speed = 1438.8249504531245\n",
            "2024-02-25 14:52:03,780.780 14171:train.py:300 speed_test_forward_backward(): speed = 1437.607537209784\n",
            "2024-02-25 14:52:08,234.234 14171:train.py:300 speed_test_forward_backward(): speed = 1437.0861882993806\n",
            "2024-02-25 14:52:11,734.734 14171:decoder.py:657    forward(): : iter=2501, avg pos = 2.9491067834896967e-05, max loss = 10.889381408691406, min loss = -3.2564257708145306e-05\n",
            "2024-02-25 14:52:12,694.694 14171:train.py:300 speed_test_forward_backward(): speed = 1435.2721919699964\n",
            "2024-02-25 14:52:17,140.140 14171:train.py:300 speed_test_forward_backward(): speed = 1439.6131791942234\n",
            "2024-02-25 14:52:21,589.589 14171:train.py:300 speed_test_forward_backward(): speed = 1438.3655295684928\n",
            "2024-02-25 14:52:26,037.037 14171:train.py:300 speed_test_forward_backward(): speed = 1438.9848412999715\n",
            "2024-02-25 14:52:30,492.492 14171:train.py:300 speed_test_forward_backward(): speed = 1436.7123799133462\n",
            "2024-02-25 14:52:34,946.946 14171:train.py:300 speed_test_forward_backward(): speed = 1436.950256451571\n",
            "2024-02-25 14:52:39,402.402 14171:train.py:300 speed_test_forward_backward(): speed = 1436.5034857632893\n",
            "2024-02-25 14:52:43,860.860 14171:train.py:300 speed_test_forward_backward(): speed = 1435.8759387323553\n",
            "2024-02-25 14:52:48,304.304 14171:train.py:300 speed_test_forward_backward(): speed = 1440.0818184607838\n",
            "2024-02-25 14:52:52,756.756 14171:train.py:300 speed_test_forward_backward(): speed = 1437.6770635800467\n",
            "2024-02-25 14:52:56,247.247 14171:decoder.py:657    forward(): : iter=2601, avg pos = 2.9615041057695635e-05, max loss = 10.810005187988281, min loss = -3.2220836146734655e-05\n",
            "2024-02-25 14:52:56,251.251 14171:decoder.py:962 forward_one_ce(): {'num_has_image': 2600, 'num_no_image': 0}\n",
            "2024-02-25 14:52:57,206.206 14171:train.py:300 speed_test_forward_backward(): speed = 1438.417324059089\n",
            "2024-02-25 14:53:01,652.652 14171:train.py:300 speed_test_forward_backward(): speed = 1439.658037349901\n",
            "2024-02-25 14:53:06,102.102 14171:train.py:300 speed_test_forward_backward(): speed = 1438.050372686566\n",
            "2024-02-25 14:53:10,556.556 14171:train.py:300 speed_test_forward_backward(): speed = 1437.1523557191108\n",
            "2024-02-25 14:53:15,005.005 14171:train.py:300 speed_test_forward_backward(): speed = 1438.7019520135148\n",
            "2024-02-25 14:53:19,454.454 14171:train.py:300 speed_test_forward_backward(): speed = 1438.3902702214361\n",
            "2024-02-25 14:53:23,902.902 14171:train.py:300 speed_test_forward_backward(): speed = 1439.0302003107765\n",
            "2024-02-25 14:53:28,353.353 14171:train.py:300 speed_test_forward_backward(): speed = 1437.9311268398426\n",
            "2024-02-25 14:53:32,809.809 14171:train.py:300 speed_test_forward_backward(): speed = 1436.64094773239\n",
            "2024-02-25 14:53:37,258.258 14171:train.py:300 speed_test_forward_backward(): speed = 1438.5004188462822\n",
            "2024-02-25 14:53:40,753.753 14171:decoder.py:657    forward(): : iter=2701, avg pos = 2.958176628453657e-05, max loss = 10.83558177947998, min loss = -3.2350679248338565e-05\n",
            "2024-02-25 14:53:41,713.713 14171:train.py:300 speed_test_forward_backward(): speed = 1436.737217524273\n",
            "2024-02-25 14:53:46,161.161 14171:train.py:300 speed_test_forward_backward(): speed = 1438.9080923440422\n",
            "2024-02-25 14:53:50,612.612 14171:train.py:300 speed_test_forward_backward(): speed = 1438.0328081028338\n",
            "2024-02-25 14:53:55,068.068 14171:train.py:300 speed_test_forward_backward(): speed = 1436.5325443223333\n",
            "2024-02-25 14:53:59,525.525 14171:train.py:300 speed_test_forward_backward(): speed = 1436.0073654665837\n",
            "2024-02-25 14:54:03,982.982 14171:train.py:300 speed_test_forward_backward(): speed = 1436.0453154755119\n",
            "2024-02-25 14:54:08,433.433 14171:train.py:300 speed_test_forward_backward(): speed = 1437.8453252041884\n",
            "2024-02-25 14:54:12,887.887 14171:train.py:300 speed_test_forward_backward(): speed = 1437.2910193063085\n",
            "2024-02-25 14:54:17,335.335 14171:train.py:300 speed_test_forward_backward(): speed = 1438.8220969595122\n",
            "2024-02-25 14:54:21,789.789 14171:train.py:300 speed_test_forward_backward(): speed = 1436.8539581088212\n",
            "2024-02-25 14:54:25,282.282 14171:decoder.py:657    forward(): : iter=2801, avg pos = 2.916622361226473e-05, max loss = 10.792962074279785, min loss = -3.23208405461628e-05\n",
            "2024-02-25 14:54:25,286.286 14171:decoder.py:962 forward_one_ce(): {'num_has_image': 2800, 'num_no_image': 0}\n",
            "2024-02-25 14:54:26,246.246 14171:train.py:300 speed_test_forward_backward(): speed = 1436.3455292426793\n",
            "2024-02-25 14:54:30,699.699 14171:train.py:300 speed_test_forward_backward(): speed = 1437.3023321112344\n",
            "2024-02-25 14:54:35,149.149 14171:train.py:300 speed_test_forward_backward(): speed = 1438.2131736534645\n",
            "2024-02-25 14:54:39,602.602 14171:train.py:300 speed_test_forward_backward(): speed = 1437.4182409020739\n",
            "2024-02-25 14:54:44,058.058 14171:train.py:300 speed_test_forward_backward(): speed = 1436.3031828159071\n",
            "2024-02-25 14:54:48,518.518 14171:train.py:300 speed_test_forward_backward(): speed = 1435.1912345564228\n",
            "2024-02-25 14:54:52,972.972 14171:train.py:300 speed_test_forward_backward(): speed = 1436.867648300189\n",
            "2024-02-25 14:54:57,433.433 14171:train.py:300 speed_test_forward_backward(): speed = 1434.7020778198487\n",
            "2024-02-25 14:55:01,897.897 14171:train.py:300 speed_test_forward_backward(): speed = 1433.90933548256\n",
            "2024-02-25 14:55:06,356.356 14171:train.py:300 speed_test_forward_backward(): speed = 1435.313556676195\n",
            "2024-02-25 14:55:09,854.854 14171:decoder.py:657    forward(): : iter=2901, avg pos = 2.9424474632833153e-05, max loss = 10.950864791870117, min loss = -3.23223794111982e-05\n",
            "2024-02-25 14:55:10,814.814 14171:train.py:300 speed_test_forward_backward(): speed = 1435.8535117921278\n",
            "2024-02-25 14:55:15,265.265 14171:train.py:300 speed_test_forward_backward(): speed = 1437.832771604561\n",
            "2024-02-25 14:55:19,729.729 14171:train.py:300 speed_test_forward_backward(): speed = 1433.7792880442128\n",
            "2024-02-25 14:55:24,184.184 14171:train.py:300 speed_test_forward_backward(): speed = 1436.7650551242946\n",
            "2024-02-25 14:55:28,643.643 14171:train.py:300 speed_test_forward_backward(): speed = 1435.4639171288438\n",
            "2024-02-25 14:55:33,096.096 14171:train.py:300 speed_test_forward_backward(): speed = 1437.421011858924\n",
            "2024-02-25 14:55:37,546.546 14171:train.py:300 speed_test_forward_backward(): speed = 1438.3199812464418\n",
            "2024-02-25 14:55:41,997.997 14171:train.py:300 speed_test_forward_backward(): speed = 1437.8871464457998\n",
            "2024-02-25 14:55:46,449.449 14171:train.py:300 speed_test_forward_backward(): speed = 1437.7176429858073\n",
            "2024-02-25 14:55:50,902.902 14171:train.py:300 speed_test_forward_backward(): speed = 1437.332269576648\n",
            "2024-02-25 14:55:54,396.396 14171:decoder.py:657    forward(): : iter=3001, avg pos = 2.93178472929867e-05, max loss = 10.835527420043945, min loss = -3.220440703444183e-05\n",
            "2024-02-25 14:55:54,399.399 14171:decoder.py:962 forward_one_ce(): {'num_has_image': 3000, 'num_no_image': 0}\n",
            "2024-02-25 14:55:55,354.354 14171:train.py:300 speed_test_forward_backward(): speed = 1437.587750756709\n",
            "2024-02-25 14:55:59,807.807 14171:train.py:300 speed_test_forward_backward(): speed = 1437.5200805847428\n",
            "2024-02-25 14:56:04,259.259 14171:train.py:300 speed_test_forward_backward(): speed = 1437.685841473654\n",
            "2024-02-25 14:56:08,712.712 14171:train.py:300 speed_test_forward_backward(): speed = 1437.0541069880376\n",
            "2024-02-25 14:56:13,158.158 14171:train.py:300 speed_test_forward_backward(): speed = 1439.8038263579206\n",
            "2024-02-25 14:56:17,609.609 14171:train.py:300 speed_test_forward_backward(): speed = 1438.16663331568\n",
            "2024-02-25 14:56:22,058.058 14171:train.py:300 speed_test_forward_backward(): speed = 1438.5259350349104\n",
            "2024-02-25 14:56:26,504.504 14171:train.py:300 speed_test_forward_backward(): speed = 1439.4051387590416\n",
            "2024-02-25 14:56:30,953.953 14171:train.py:300 speed_test_forward_backward(): speed = 1438.869682372878\n",
            "2024-02-25 14:56:35,400.400 14171:train.py:300 speed_test_forward_backward(): speed = 1439.1032590150403\n",
            "2024-02-25 14:56:38,892.892 14171:decoder.py:657    forward(): : iter=3101, avg pos = 2.9285507480381057e-05, max loss = 10.818451881408691, min loss = -3.209968417650089e-05\n",
            "2024-02-25 14:56:39,850.850 14171:train.py:300 speed_test_forward_backward(): speed = 1438.3646047007735\n",
            "2024-02-25 14:56:44,296.296 14171:train.py:300 speed_test_forward_backward(): speed = 1439.7273761092924\n",
            "2024-02-25 14:56:48,741.741 14171:train.py:300 speed_test_forward_backward(): speed = 1439.7438238106465\n",
            "2024-02-25 14:56:53,190.190 14171:train.py:300 speed_test_forward_backward(): speed = 1438.6403450265661\n",
            "2024-02-25 14:56:57,645.645 14171:train.py:300 speed_test_forward_backward(): speed = 1436.6823913727378\n",
            "2024-02-25 14:57:02,097.097 14171:train.py:300 speed_test_forward_backward(): speed = 1437.799270739979\n",
            "2024-02-25 14:57:06,551.551 14171:train.py:300 speed_test_forward_backward(): speed = 1436.8059675880334\n",
            "2024-02-25 14:57:11,004.004 14171:train.py:300 speed_test_forward_backward(): speed = 1437.5752786420328\n",
            "2024-02-25 14:57:15,452.452 14171:train.py:300 speed_test_forward_backward(): speed = 1438.938405275039\n",
            "2024-02-25 14:57:19,903.903 14171:train.py:300 speed_test_forward_backward(): speed = 1437.7801720951945\n",
            "2024-02-25 14:57:23,392.392 14171:decoder.py:657    forward(): : iter=3201, avg pos = 2.917045640060678e-05, max loss = 10.820201873779297, min loss = -3.2552125048823655e-05\n",
            "2024-02-25 14:57:23,396.396 14171:decoder.py:962 forward_one_ce(): {'num_has_image': 3200, 'num_no_image': 0}\n",
            "2024-02-25 14:57:24,352.352 14171:train.py:300 speed_test_forward_backward(): speed = 1438.7054219006466\n",
            "2024-02-25 14:57:28,799.799 14171:train.py:300 speed_test_forward_backward(): speed = 1439.3291938960556\n",
            "2024-02-25 14:57:33,246.246 14171:train.py:300 speed_test_forward_backward(): speed = 1439.3757323277766\n",
            "2024-02-25 14:57:37,695.695 14171:train.py:300 speed_test_forward_backward(): speed = 1438.6229973277516\n",
            "2024-02-25 14:57:42,146.146 14171:train.py:300 speed_test_forward_backward(): speed = 1437.8549523462784\n",
            "2024-02-25 14:57:46,596.596 14171:train.py:300 speed_test_forward_backward(): speed = 1438.2228057220848\n",
            "2024-02-25 14:57:51,047.047 14171:train.py:300 speed_test_forward_backward(): speed = 1438.0818821598273\n",
            "2024-02-25 14:57:55,499.499 14171:train.py:300 speed_test_forward_backward(): speed = 1437.7186440247676\n",
            "2024-02-25 14:57:59,945.945 14171:train.py:300 speed_test_forward_backward(): speed = 1439.4414160645433\n",
            "2024-02-25 14:58:04,399.399 14171:train.py:300 speed_test_forward_backward(): speed = 1437.1387370428995\n",
            "2024-02-25 14:58:07,895.895 14171:decoder.py:657    forward(): : iter=3301, avg pos = 2.9480288503691554e-05, max loss = 10.906472206115723, min loss = -3.211041621398181e-05\n",
            "2024-02-25 14:58:08,855.855 14171:train.py:300 speed_test_forward_backward(): speed = 1436.3402261958454\n",
            "2024-02-25 14:58:13,304.304 14171:train.py:300 speed_test_forward_backward(): speed = 1438.6454337642465\n",
            "2024-02-25 14:58:17,761.761 14171:train.py:300 speed_test_forward_backward(): speed = 1436.2047427874486\n",
            "2024-02-25 14:58:22,215.215 14171:train.py:300 speed_test_forward_backward(): speed = 1436.976025369662\n",
            "2024-02-25 14:58:26,663.663 14171:train.py:300 speed_test_forward_backward(): speed = 1439.049023596965\n",
            "2024-02-25 14:58:31,117.117 14171:train.py:300 speed_test_forward_backward(): speed = 1436.9131815998558\n",
            "2024-02-25 14:58:35,568.568 14171:train.py:300 speed_test_forward_backward(): speed = 1437.969871867773\n",
            "2024-02-25 14:58:40,021.021 14171:train.py:300 speed_test_forward_backward(): speed = 1437.1944444459316\n",
            "2024-02-25 14:58:44,466.466 14171:train.py:300 speed_test_forward_backward(): speed = 1440.020556743344\n",
            "2024-02-25 14:58:48,918.918 14171:train.py:300 speed_test_forward_backward(): speed = 1437.7068626545733\n",
            "2024-02-25 14:58:52,410.410 14171:decoder.py:657    forward(): : iter=3401, avg pos = 2.917621714004781e-05, max loss = 10.916426658630371, min loss = -3.2213181839324534e-05\n",
            "2024-02-25 14:58:52,414.414 14171:decoder.py:962 forward_one_ce(): {'num_has_image': 3400, 'num_no_image': 0}\n",
            "2024-02-25 14:58:53,368.368 14171:train.py:300 speed_test_forward_backward(): speed = 1438.373468065334\n",
            "2024-02-25 14:58:57,822.822 14171:train.py:300 speed_test_forward_backward(): speed = 1436.9905640626046\n",
            "2024-02-25 14:59:02,274.274 14171:train.py:300 speed_test_forward_backward(): speed = 1437.787411037942\n",
            "2024-02-25 14:59:06,731.731 14171:train.py:300 speed_test_forward_backward(): speed = 1435.9115006936024\n",
            "2024-02-25 14:59:11,186.186 14171:train.py:300 speed_test_forward_backward(): speed = 1436.8258094338707\n",
            "2024-02-25 14:59:15,638.638 14171:train.py:300 speed_test_forward_backward(): speed = 1437.6165452307132\n",
            "2024-02-25 14:59:20,095.095 14171:train.py:300 speed_test_forward_backward(): speed = 1435.7618144006287\n",
            "2024-02-25 14:59:24,546.546 14171:train.py:300 speed_test_forward_backward(): speed = 1438.2898484937136\n",
            "2024-02-25 14:59:29,000.000 14171:train.py:300 speed_test_forward_backward(): speed = 1436.9671792189745\n",
            "2024-02-25 14:59:33,454.454 14171:train.py:300 speed_test_forward_backward(): speed = 1436.9491795616802\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# single image, captioning\n",
        "!AZFUSE_TSV_USE_FUSE=1 python -m generativeimage2text.inference -p \"{'type': 'test_git_inference_single_image', \\\n",
        "      'image_path': 'aux_data/images/1.jpg', \\\n",
        "      'model_name': 'GIT_BASE', \\\n",
        "      'prefix': '', \\\n",
        "}\"\n",
        "# single image, question answering\n",
        "!AZFUSE_TSV_USE_FUSE=1 python -m generativeimage2text.inference -p \"{'type': 'test_git_inference_single_image', \\\n",
        "      'image_path': 'aux_data/images/1.jpg', \\\n",
        "      'model_name': 'GIT_BASE_VQAv2', \\\n",
        "      'prefix': 'what is it?', \\\n",
        "}\"\n",
        "# multiple images, captioning\n",
        "!AZFUSE_TSV_USE_FUSE=1 python -m generativeimage2text.inference -p \"{'type': 'test_git_inference_single_image', \\\n",
        "      'image_path': ['aux_data/images/1.jpg', 'aux_data/images/1.jpg', 'aux_data/images/1.jpg', 'aux_data/images/1.jpg', 'aux_data/images/1.jpg', 'aux_data/images/1.jpg'], \\\n",
        "      'model_name': 'GIT_BASE_VATEX', \\\n",
        "      'prefix': '', \\\n",
        "}\"\n",
        "# multiple images, question answering\n",
        "!AZFUSE_TSV_USE_FUSE=1 python -m generativeimage2text.inference -p \"{'type': 'test_git_inference_single_image', \\\n",
        "      'image_path': ['aux_data/images/1.jpg', 'aux_data/images/1.jpg', 'aux_data/images/1.jpg', 'aux_data/images/1.jpg', 'aux_data/images/1.jpg', 'aux_data/images/1.jpg'], \\\n",
        "      'model_name': 'GIT_BASE_MSRVTT_QA', \\\n",
        "      'prefix': 'what is it?', \\\n",
        "}\""
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "5RCkApMEVoyY",
        "outputId": "b0b6872d-5879-4ae1-bcd1-dff19ff3a8a2"
      },
      "execution_count": 4,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "2024-02-25 12:56:52,618.618 7181:inference.py:318   <module>(): param:\n",
            "{'image_path': 'aux_data/images/1.jpg',\n",
            " 'model_name': 'GIT_BASE',\n",
            " 'prefix': '',\n",
            " 'type': 'test_git_inference_single_image'}\n",
            "2024-02-25 12:56:57,744.744 7181:cloud_storage.py:1150 az_download_once(): if sync, no need to save to temp first\n",
            "2024-02-25 12:56:57,745.745 7181:common.py:324    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE/snapshot/model.pt /tmp/publicgit/output/GIT_BASE/snapshot/model.pt\n",
            "2024-02-25 12:56:57,746.746 7181:cloud_storage.py:1211 az_download_once(): ['azcopy',\n",
            " 'cp',\n",
            " 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE/snapshot/model.pt',\n",
            " '/tmp/publicgit/output/GIT_BASE/snapshot/model.pt']\n",
            "2024-02-25 12:56:57,746.746 7181:common.py:234 limited_retry_agent(): fails with \n",
            "[Errno 2] No such file or directory: 'azcopy': tried 1/5-th time\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "2024-02-25 12:57:01,632.632 7181:cloud_storage.py:1150 az_download_once(): if sync, no need to save to temp first\n",
            "2024-02-25 12:57:01,633.633 7181:common.py:324    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE/snapshot/model.pt /tmp/publicgit/output/GIT_BASE/snapshot/model.pt\n",
            "2024-02-25 12:57:01,634.634 7181:cloud_storage.py:1211 az_download_once(): ['azcopy',\n",
            " 'cp',\n",
            " 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE/snapshot/model.pt',\n",
            " '/tmp/publicgit/output/GIT_BASE/snapshot/model.pt']\n",
            "2024-02-25 12:57:01,634.634 7181:common.py:234 limited_retry_agent(): fails with \n",
            "[Errno 2] No such file or directory: 'azcopy': tried 2/5-th time\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "2024-02-25 12:57:05,715.715 7181:cloud_storage.py:1150 az_download_once(): if sync, no need to save to temp first\n",
            "2024-02-25 12:57:05,715.715 7181:common.py:324    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE/snapshot/model.pt /tmp/publicgit/output/GIT_BASE/snapshot/model.pt\n",
            "2024-02-25 12:57:05,716.716 7181:cloud_storage.py:1211 az_download_once(): ['azcopy',\n",
            " 'cp',\n",
            " 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE/snapshot/model.pt',\n",
            " '/tmp/publicgit/output/GIT_BASE/snapshot/model.pt']\n",
            "2024-02-25 12:57:05,716.716 7181:common.py:234 limited_retry_agent(): fails with \n",
            "[Errno 2] No such file or directory: 'azcopy': tried 3/5-th time\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "2024-02-25 12:57:10,580.580 7181:cloud_storage.py:1150 az_download_once(): if sync, no need to save to temp first\n",
            "2024-02-25 12:57:10,580.580 7181:common.py:324    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE/snapshot/model.pt /tmp/publicgit/output/GIT_BASE/snapshot/model.pt\n",
            "2024-02-25 12:57:10,582.582 7181:cloud_storage.py:1211 az_download_once(): ['azcopy',\n",
            " 'cp',\n",
            " 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE/snapshot/model.pt',\n",
            " '/tmp/publicgit/output/GIT_BASE/snapshot/model.pt']\n",
            "2024-02-25 12:57:10,582.582 7181:common.py:234 limited_retry_agent(): fails with \n",
            "[Errno 2] No such file or directory: 'azcopy': tried 4/5-th time\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "2024-02-25 12:57:11,649.649 7181:cloud_storage.py:1150 az_download_once(): if sync, no need to save to temp first\n",
            "2024-02-25 12:57:11,649.649 7181:common.py:324    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE/snapshot/model.pt /tmp/publicgit/output/GIT_BASE/snapshot/model.pt\n",
            "2024-02-25 12:57:11,650.650 7181:cloud_storage.py:1211 az_download_once(): ['azcopy',\n",
            " 'cp',\n",
            " 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE/snapshot/model.pt',\n",
            " '/tmp/publicgit/output/GIT_BASE/snapshot/model.pt']\n",
            "2024-02-25 12:57:11,650.650 7181:common.py:234 limited_retry_agent(): fails with \n",
            "[Errno 2] No such file or directory: 'azcopy': tried 5/5-th time\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"/content/GenerativeImage2Text/generativeimage2text/inference.py\", line 321, in <module>\n",
            "    locals()[function_name](**kwargs)\n",
            "  File \"/content/GenerativeImage2Text/generativeimage2text/inference.py\", line 85, in test_git_inference_single_image\n",
            "    checkpoint = torch_load(pretrained)['model']\n",
            "  File \"/content/GenerativeImage2Text/generativeimage2text/torch_common.py\", line 42, in torch_load\n",
            "    with File.open(filename, 'rb') as fp:\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/azfuse.py\", line 50, in open\n",
            "    return cls.fuser.open(fname, mode)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 497, in open\n",
            "    return self.open_to_read(info, mode)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 537, in open_to_read\n",
            "    self.ensure_remote_to_cache(remote_file, cache_file, cloud,\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 644, in ensure_remote_to_cache\n",
            "    self.remote_to_cache(remote_file, cache_file, cloud, cache_lock)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 616, in remote_to_cache\n",
            "    cloud.az_download(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1130, in az_download\n",
            "    limited_retry_agent(retry, self.az_download_once,\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "2024-02-25 12:57:15,609.609 7285:inference.py:318   <module>(): param:\n",
            "{'image_path': 'aux_data/images/1.jpg',\n",
            " 'model_name': 'GIT_BASE_VQAv2',\n",
            " 'prefix': 'what is it?',\n",
            " 'type': 'test_git_inference_single_image'}\n",
            "2024-02-25 12:57:20,770.770 7285:cloud_storage.py:1150 az_download_once(): if sync, no need to save to temp first\n",
            "2024-02-25 12:57:20,770.770 7285:common.py:324    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE_VQAv2/snapshot/model.pt /tmp/publicgit/output/GIT_BASE_VQAv2/snapshot/model.pt\n",
            "2024-02-25 12:57:20,772.772 7285:cloud_storage.py:1211 az_download_once(): ['azcopy',\n",
            " 'cp',\n",
            " 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE_VQAv2/snapshot/model.pt',\n",
            " '/tmp/publicgit/output/GIT_BASE_VQAv2/snapshot/model.pt']\n",
            "2024-02-25 12:57:20,772.772 7285:common.py:234 limited_retry_agent(): fails with \n",
            "[Errno 2] No such file or directory: 'azcopy': tried 1/5-th time\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "2024-02-25 12:57:24,329.329 7285:cloud_storage.py:1150 az_download_once(): if sync, no need to save to temp first\n",
            "2024-02-25 12:57:24,329.329 7285:common.py:324    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE_VQAv2/snapshot/model.pt /tmp/publicgit/output/GIT_BASE_VQAv2/snapshot/model.pt\n",
            "2024-02-25 12:57:24,330.330 7285:cloud_storage.py:1211 az_download_once(): ['azcopy',\n",
            " 'cp',\n",
            " 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE_VQAv2/snapshot/model.pt',\n",
            " '/tmp/publicgit/output/GIT_BASE_VQAv2/snapshot/model.pt']\n",
            "2024-02-25 12:57:24,330.330 7285:common.py:234 limited_retry_agent(): fails with \n",
            "[Errno 2] No such file or directory: 'azcopy': tried 2/5-th time\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "2024-02-25 12:57:27,756.756 7285:cloud_storage.py:1150 az_download_once(): if sync, no need to save to temp first\n",
            "2024-02-25 12:57:27,756.756 7285:common.py:324    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE_VQAv2/snapshot/model.pt /tmp/publicgit/output/GIT_BASE_VQAv2/snapshot/model.pt\n",
            "2024-02-25 12:57:27,758.758 7285:cloud_storage.py:1211 az_download_once(): ['azcopy',\n",
            " 'cp',\n",
            " 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE_VQAv2/snapshot/model.pt',\n",
            " '/tmp/publicgit/output/GIT_BASE_VQAv2/snapshot/model.pt']\n",
            "2024-02-25 12:57:27,758.758 7285:common.py:234 limited_retry_agent(): fails with \n",
            "[Errno 2] No such file or directory: 'azcopy': tried 3/5-th time\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "2024-02-25 12:57:30,415.415 7285:cloud_storage.py:1150 az_download_once(): if sync, no need to save to temp first\n",
            "2024-02-25 12:57:30,416.416 7285:common.py:324    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE_VQAv2/snapshot/model.pt /tmp/publicgit/output/GIT_BASE_VQAv2/snapshot/model.pt\n",
            "2024-02-25 12:57:30,417.417 7285:cloud_storage.py:1211 az_download_once(): ['azcopy',\n",
            " 'cp',\n",
            " 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE_VQAv2/snapshot/model.pt',\n",
            " '/tmp/publicgit/output/GIT_BASE_VQAv2/snapshot/model.pt']\n",
            "2024-02-25 12:57:30,417.417 7285:common.py:234 limited_retry_agent(): fails with \n",
            "[Errno 2] No such file or directory: 'azcopy': tried 4/5-th time\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "2024-02-25 12:57:32,745.745 7285:cloud_storage.py:1150 az_download_once(): if sync, no need to save to temp first\n",
            "2024-02-25 12:57:32,745.745 7285:common.py:324    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE_VQAv2/snapshot/model.pt /tmp/publicgit/output/GIT_BASE_VQAv2/snapshot/model.pt\n",
            "2024-02-25 12:57:32,746.746 7285:cloud_storage.py:1211 az_download_once(): ['azcopy',\n",
            " 'cp',\n",
            " 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE_VQAv2/snapshot/model.pt',\n",
            " '/tmp/publicgit/output/GIT_BASE_VQAv2/snapshot/model.pt']\n",
            "2024-02-25 12:57:32,746.746 7285:common.py:234 limited_retry_agent(): fails with \n",
            "[Errno 2] No such file or directory: 'azcopy': tried 5/5-th time\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"/content/GenerativeImage2Text/generativeimage2text/inference.py\", line 321, in <module>\n",
            "    locals()[function_name](**kwargs)\n",
            "  File \"/content/GenerativeImage2Text/generativeimage2text/inference.py\", line 85, in test_git_inference_single_image\n",
            "    checkpoint = torch_load(pretrained)['model']\n",
            "  File \"/content/GenerativeImage2Text/generativeimage2text/torch_common.py\", line 42, in torch_load\n",
            "    with File.open(filename, 'rb') as fp:\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/azfuse.py\", line 50, in open\n",
            "    return cls.fuser.open(fname, mode)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 497, in open\n",
            "    return self.open_to_read(info, mode)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 537, in open_to_read\n",
            "    self.ensure_remote_to_cache(remote_file, cache_file, cloud,\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 644, in ensure_remote_to_cache\n",
            "    self.remote_to_cache(remote_file, cache_file, cloud, cache_lock)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 616, in remote_to_cache\n",
            "    cloud.az_download(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1130, in az_download\n",
            "    limited_retry_agent(retry, self.az_download_once,\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "2024-02-25 12:57:37,091.091 7381:inference.py:318   <module>(): param:\n",
            "{'image_path': ['aux_data/images/1.jpg',\n",
            "                'aux_data/images/1.jpg',\n",
            "                'aux_data/images/1.jpg',\n",
            "                'aux_data/images/1.jpg',\n",
            "                'aux_data/images/1.jpg',\n",
            "                'aux_data/images/1.jpg'],\n",
            " 'model_name': 'GIT_BASE_VATEX',\n",
            " 'prefix': '',\n",
            " 'type': 'test_git_inference_single_image'}\n",
            "2024-02-25 12:57:41,719.719 7381:decoder.py:832   __init__(): creating temperal embedding\n",
            "2024-02-25 12:57:42,269.269 7381:cloud_storage.py:1150 az_download_once(): if sync, no need to save to temp first\n",
            "2024-02-25 12:57:42,270.270 7381:common.py:324    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE_VATEX/snapshot/model.pt /tmp/publicgit/output/GIT_BASE_VATEX/snapshot/model.pt\n",
            "2024-02-25 12:57:42,271.271 7381:cloud_storage.py:1211 az_download_once(): ['azcopy',\n",
            " 'cp',\n",
            " 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE_VATEX/snapshot/model.pt',\n",
            " '/tmp/publicgit/output/GIT_BASE_VATEX/snapshot/model.pt']\n",
            "2024-02-25 12:57:42,271.271 7381:common.py:234 limited_retry_agent(): fails with \n",
            "[Errno 2] No such file or directory: 'azcopy': tried 1/5-th time\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "2024-02-25 12:57:44,772.772 7381:cloud_storage.py:1150 az_download_once(): if sync, no need to save to temp first\n",
            "2024-02-25 12:57:44,773.773 7381:common.py:324    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE_VATEX/snapshot/model.pt /tmp/publicgit/output/GIT_BASE_VATEX/snapshot/model.pt\n",
            "2024-02-25 12:57:44,774.774 7381:cloud_storage.py:1211 az_download_once(): ['azcopy',\n",
            " 'cp',\n",
            " 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE_VATEX/snapshot/model.pt',\n",
            " '/tmp/publicgit/output/GIT_BASE_VATEX/snapshot/model.pt']\n",
            "2024-02-25 12:57:44,774.774 7381:common.py:234 limited_retry_agent(): fails with \n",
            "[Errno 2] No such file or directory: 'azcopy': tried 2/5-th time\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "2024-02-25 12:57:49,757.757 7381:cloud_storage.py:1150 az_download_once(): if sync, no need to save to temp first\n",
            "2024-02-25 12:57:49,757.757 7381:common.py:324    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE_VATEX/snapshot/model.pt /tmp/publicgit/output/GIT_BASE_VATEX/snapshot/model.pt\n",
            "2024-02-25 12:57:49,758.758 7381:cloud_storage.py:1211 az_download_once(): ['azcopy',\n",
            " 'cp',\n",
            " 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE_VATEX/snapshot/model.pt',\n",
            " '/tmp/publicgit/output/GIT_BASE_VATEX/snapshot/model.pt']\n",
            "2024-02-25 12:57:49,758.758 7381:common.py:234 limited_retry_agent(): fails with \n",
            "[Errno 2] No such file or directory: 'azcopy': tried 3/5-th time\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "2024-02-25 12:57:50,904.904 7381:cloud_storage.py:1150 az_download_once(): if sync, no need to save to temp first\n",
            "2024-02-25 12:57:50,904.904 7381:common.py:324    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE_VATEX/snapshot/model.pt /tmp/publicgit/output/GIT_BASE_VATEX/snapshot/model.pt\n",
            "2024-02-25 12:57:50,905.905 7381:cloud_storage.py:1211 az_download_once(): ['azcopy',\n",
            " 'cp',\n",
            " 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE_VATEX/snapshot/model.pt',\n",
            " '/tmp/publicgit/output/GIT_BASE_VATEX/snapshot/model.pt']\n",
            "2024-02-25 12:57:50,905.905 7381:common.py:234 limited_retry_agent(): fails with \n",
            "[Errno 2] No such file or directory: 'azcopy': tried 4/5-th time\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "2024-02-25 12:57:54,135.135 7381:cloud_storage.py:1150 az_download_once(): if sync, no need to save to temp first\n",
            "2024-02-25 12:57:54,136.136 7381:common.py:324    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE_VATEX/snapshot/model.pt /tmp/publicgit/output/GIT_BASE_VATEX/snapshot/model.pt\n",
            "2024-02-25 12:57:54,137.137 7381:cloud_storage.py:1211 az_download_once(): ['azcopy',\n",
            " 'cp',\n",
            " 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE_VATEX/snapshot/model.pt',\n",
            " '/tmp/publicgit/output/GIT_BASE_VATEX/snapshot/model.pt']\n",
            "2024-02-25 12:57:54,137.137 7381:common.py:234 limited_retry_agent(): fails with \n",
            "[Errno 2] No such file or directory: 'azcopy': tried 5/5-th time\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"/content/GenerativeImage2Text/generativeimage2text/inference.py\", line 321, in <module>\n",
            "    locals()[function_name](**kwargs)\n",
            "  File \"/content/GenerativeImage2Text/generativeimage2text/inference.py\", line 85, in test_git_inference_single_image\n",
            "    checkpoint = torch_load(pretrained)['model']\n",
            "  File \"/content/GenerativeImage2Text/generativeimage2text/torch_common.py\", line 42, in torch_load\n",
            "    with File.open(filename, 'rb') as fp:\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/azfuse.py\", line 50, in open\n",
            "    return cls.fuser.open(fname, mode)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 497, in open\n",
            "    return self.open_to_read(info, mode)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 537, in open_to_read\n",
            "    self.ensure_remote_to_cache(remote_file, cache_file, cloud,\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 644, in ensure_remote_to_cache\n",
            "    self.remote_to_cache(remote_file, cache_file, cloud, cache_lock)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 616, in remote_to_cache\n",
            "    cloud.az_download(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1130, in az_download\n",
            "    limited_retry_agent(retry, self.az_download_once,\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "2024-02-25 12:57:58,721.721 7477:inference.py:318   <module>(): param:\n",
            "{'image_path': ['aux_data/images/1.jpg',\n",
            "                'aux_data/images/1.jpg',\n",
            "                'aux_data/images/1.jpg',\n",
            "                'aux_data/images/1.jpg',\n",
            "                'aux_data/images/1.jpg',\n",
            "                'aux_data/images/1.jpg'],\n",
            " 'model_name': 'GIT_BASE_MSRVTT_QA',\n",
            " 'prefix': 'what is it?',\n",
            " 'type': 'test_git_inference_single_image'}\n",
            "2024-02-25 12:58:03,350.350 7477:decoder.py:832   __init__(): creating temperal embedding\n",
            "2024-02-25 12:58:03,896.896 7477:cloud_storage.py:1150 az_download_once(): if sync, no need to save to temp first\n",
            "2024-02-25 12:58:03,897.897 7477:common.py:324    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE_MSRVTT_QA/snapshot/model.pt /tmp/publicgit/output/GIT_BASE_MSRVTT_QA/snapshot/model.pt\n",
            "2024-02-25 12:58:03,898.898 7477:cloud_storage.py:1211 az_download_once(): ['azcopy',\n",
            " 'cp',\n",
            " 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE_MSRVTT_QA/snapshot/model.pt',\n",
            " '/tmp/publicgit/output/GIT_BASE_MSRVTT_QA/snapshot/model.pt']\n",
            "2024-02-25 12:58:03,898.898 7477:common.py:234 limited_retry_agent(): fails with \n",
            "[Errno 2] No such file or directory: 'azcopy': tried 1/5-th time\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "2024-02-25 12:58:04,700.700 7477:cloud_storage.py:1150 az_download_once(): if sync, no need to save to temp first\n",
            "2024-02-25 12:58:04,701.701 7477:common.py:324    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE_MSRVTT_QA/snapshot/model.pt /tmp/publicgit/output/GIT_BASE_MSRVTT_QA/snapshot/model.pt\n",
            "2024-02-25 12:58:04,702.702 7477:cloud_storage.py:1211 az_download_once(): ['azcopy',\n",
            " 'cp',\n",
            " 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE_MSRVTT_QA/snapshot/model.pt',\n",
            " '/tmp/publicgit/output/GIT_BASE_MSRVTT_QA/snapshot/model.pt']\n",
            "2024-02-25 12:58:04,702.702 7477:common.py:234 limited_retry_agent(): fails with \n",
            "[Errno 2] No such file or directory: 'azcopy': tried 2/5-th time\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "2024-02-25 12:58:07,058.058 7477:cloud_storage.py:1150 az_download_once(): if sync, no need to save to temp first\n",
            "2024-02-25 12:58:07,058.058 7477:common.py:324    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE_MSRVTT_QA/snapshot/model.pt /tmp/publicgit/output/GIT_BASE_MSRVTT_QA/snapshot/model.pt\n",
            "2024-02-25 12:58:07,059.059 7477:cloud_storage.py:1211 az_download_once(): ['azcopy',\n",
            " 'cp',\n",
            " 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE_MSRVTT_QA/snapshot/model.pt',\n",
            " '/tmp/publicgit/output/GIT_BASE_MSRVTT_QA/snapshot/model.pt']\n",
            "2024-02-25 12:58:07,060.060 7477:common.py:234 limited_retry_agent(): fails with \n",
            "[Errno 2] No such file or directory: 'azcopy': tried 3/5-th time\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "2024-02-25 12:58:09,663.663 7477:cloud_storage.py:1150 az_download_once(): if sync, no need to save to temp first\n",
            "2024-02-25 12:58:09,663.663 7477:common.py:324    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE_MSRVTT_QA/snapshot/model.pt /tmp/publicgit/output/GIT_BASE_MSRVTT_QA/snapshot/model.pt\n",
            "2024-02-25 12:58:09,665.665 7477:cloud_storage.py:1211 az_download_once(): ['azcopy',\n",
            " 'cp',\n",
            " 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE_MSRVTT_QA/snapshot/model.pt',\n",
            " '/tmp/publicgit/output/GIT_BASE_MSRVTT_QA/snapshot/model.pt']\n",
            "2024-02-25 12:58:09,665.665 7477:common.py:234 limited_retry_agent(): fails with \n",
            "[Errno 2] No such file or directory: 'azcopy': tried 4/5-th time\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "2024-02-25 12:58:13,695.695 7477:cloud_storage.py:1150 az_download_once(): if sync, no need to save to temp first\n",
            "2024-02-25 12:58:13,695.695 7477:common.py:324    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE_MSRVTT_QA/snapshot/model.pt /tmp/publicgit/output/GIT_BASE_MSRVTT_QA/snapshot/model.pt\n",
            "2024-02-25 12:58:13,696.696 7477:cloud_storage.py:1211 az_download_once(): ['azcopy',\n",
            " 'cp',\n",
            " 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE_MSRVTT_QA/snapshot/model.pt',\n",
            " '/tmp/publicgit/output/GIT_BASE_MSRVTT_QA/snapshot/model.pt']\n",
            "2024-02-25 12:58:13,696.696 7477:common.py:234 limited_retry_agent(): fails with \n",
            "[Errno 2] No such file or directory: 'azcopy': tried 5/5-th time\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"/content/GenerativeImage2Text/generativeimage2text/inference.py\", line 321, in <module>\n",
            "    locals()[function_name](**kwargs)\n",
            "  File \"/content/GenerativeImage2Text/generativeimage2text/inference.py\", line 85, in test_git_inference_single_image\n",
            "    checkpoint = torch_load(pretrained)['model']\n",
            "  File \"/content/GenerativeImage2Text/generativeimage2text/torch_common.py\", line 42, in torch_load\n",
            "    with File.open(filename, 'rb') as fp:\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/azfuse.py\", line 50, in open\n",
            "    return cls.fuser.open(fname, mode)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 497, in open\n",
            "    return self.open_to_read(info, mode)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 537, in open_to_read\n",
            "    self.ensure_remote_to_cache(remote_file, cache_file, cloud,\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 644, in ensure_remote_to_cache\n",
            "    self.remote_to_cache(remote_file, cache_file, cloud, cache_lock)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 616, in remote_to_cache\n",
            "    cloud.az_download(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1130, in az_download\n",
            "    limited_retry_agent(retry, self.az_download_once,\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "1bG1PkhuVuYq"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}