{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "gpuType": "T4"
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    },
    "accelerator": "GPU"
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "EyrwRm_WLdeG",
        "outputId": "e90782a7-4681-499a-fcee-67af9323b292"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Cloning into 'GenerativeImage2Text'...\n",
            "remote: Enumerating objects: 160, done.\u001b[K\n",
            "remote: Counting objects: 100% (63/63), done.\u001b[K\n",
            "remote: Compressing objects: 100% (37/37), done.\u001b[K\n",
            "remote: Total 160 (delta 44), reused 33 (delta 26), pack-reused 97\u001b[K\n",
            "Receiving objects: 100% (160/160), 501.71 KiB | 6.19 MiB/s, done.\n",
            "Resolving deltas: 100% (63/63), done.\n",
            "/content/GenerativeImage2Text\n"
          ]
        }
      ],
      "source": [
        "!git clone https://github.com/microsoft/GenerativeImage2Text.git\n",
        "%cd GenerativeImage2Text\n",
        "!pip install -r requirements.txt\n",
        "!python setup.py build develop"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "from .common import Config\n",
        "import json\n",
        "import os.path as op\n",
        "from .common import qd_tqdm as tqdm\n",
        "from .common import json_dump\n",
        "from .common import pilimg_from_base64\n",
        "from .torch_common import recursive_to_device\n",
        "from .tsv_io import TSVFile, tsv_writer, tsv_reader\n",
        "from .common import write_to_file\n",
        "import torch\n",
        "import PIL\n",
        "from pprint import pformat\n",
        "import logging\n",
        "from transformers import BertTokenizer\n",
        "import torchvision.transforms as transforms\n",
        "from torchvision.transforms import Compose, Resize, CenterCrop, ToTensor, Normalize\n",
        "from PIL import Image\n",
        "from azfuse import File\n",
        "\n",
        "from .common import init_logging\n",
        "from .common import parse_general_args\n",
        "from .tsv_io import load_from_yaml_file\n",
        "from .torch_common import torch_load\n",
        "from .torch_common import load_state_dict\n",
        "from .torch_common import resize_2d_pos_embed\n",
        "from .layers.CLIP import clip\n",
        "from .layers.decoder import (TransformerDecoderTextualHead,\n",
        "                             AutoRegressiveBeamSearch, GeneratorWithBeamSearch)\n",
        "from .layers.decoder import CaptioningModel\n",
        "from .process_image import load_image_by_pil\n",
        "from .data_layer.transform import RenameKey, SelectTransform\n",
        "from .data_layer.transform import ImageTransform2Dict\n",
        "from .data_layer.transform import get_inception_train_transform\n",
        "from .data_layer.builder import collate_fn\n",
        "from .model import get_git_model"
      ],
      "metadata": {
        "id": "0h-ee6jd7i5K"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "def get_data(image_file, prefix, target, tokenizer, image_transform):\n",
        "    max_text_len = 40\n",
        "    prefix_encoding = tokenizer(\n",
        "        prefix, padding='do_not_pad',\n",
        "        add_special_tokens=False,\n",
        "        truncation=True, max_length=max_text_len)\n",
        "    target_encoding = tokenizer(\n",
        "        target, padding='do_not_pad',\n",
        "        add_special_tokens=False,\n",
        "        truncation=True, max_length=max_text_len)\n",
        "    need_predict = [0] * len(prefix_encoding['input_ids']) + [1] * len(target_encoding['input_ids'])\n",
        "    payload = prefix_encoding['input_ids'] + target_encoding['input_ids']\n",
        "    if len(payload) > max_text_len:\n",
        "        payload = payload[-(max_text_len - 2):]\n",
        "        need_predict = need_predict[-(max_text_len - 2):]\n",
        "    input_ids = [tokenizer.cls_token_id] + payload + [tokenizer.sep_token_id]\n",
        "    need_predict = [0] + need_predict + [1]\n",
        "\n",
        "    im = load_image_by_pil(image_file)\n",
        "\n",
        "    data = {\n",
        "        'caption_tokens': torch.tensor(input_ids),\n",
        "        #'caption_lengths': len(input_ids),\n",
        "        'need_predict': torch.tensor(need_predict),\n",
        "        'image': im,\n",
        "        # 'rect' field can be fed in 'caption', which tells the bounding box\n",
        "        # region of the image that is described by the caption. In this case,\n",
        "        # we can optionally crop the region.\n",
        "        'caption': {},\n",
        "        # this iteration can be used for crop-size selection so that all GPUs\n",
        "        # can process the image with the same input size\n",
        "        'iteration': 0,\n",
        "    }\n",
        "    data = image_transform(data)\n",
        "\n",
        "    return data\n",
        "\n",
        "def get_image_transform(cfg):\n",
        "    return get_multi_scale_image_transform(cfg, is_train=True)\n",
        "\n",
        "def get_default_mean():\n",
        "    return [0.485, 0.456, 0.406]\n",
        "\n",
        "def get_default_std():\n",
        "    return [0.229, 0.224, 0.225]\n",
        "\n",
        "def get_transform_image_norm(cfg, default=None):\n",
        "    if cfg.data_normalize == 'default':\n",
        "        normalize = transforms.Normalize(\n",
        "            mean=get_default_mean(), std=get_default_std())\n",
        "    elif cfg.data_normalize == 'clip':\n",
        "        # clip model\n",
        "        normalize = transforms.Normalize(\n",
        "            (0.48145466, 0.4578275, 0.40821073), (0.26862954, 0.26130258, 0.27577711))\n",
        "    else:\n",
        "        raise NotImplementedError(cfg.data_normalize)\n",
        "    return normalize\n",
        "\n",
        "def get_transform_vit_default(cfg, is_train):\n",
        "    default_normalize = transforms.Normalize(\n",
        "            mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])\n",
        "    normalize = get_transform_image_norm(cfg, default_normalize)\n",
        "    transform = get_inception_train_transform(\n",
        "        bgr2rgb=True,\n",
        "        crop_size=cfg.train_crop_size,\n",
        "        normalize=normalize,\n",
        "        small_scale=cfg.input_small_scale,\n",
        "        no_color_jitter=cfg.no_color_jitter,\n",
        "        no_flip=cfg.no_flip,\n",
        "        no_aspect_dist=cfg.no_aspect_dist,\n",
        "        resize_crop=cfg.resize_crop,\n",
        "        max_size=cfg.train_max_size,\n",
        "        interpolation=cfg.interpolation or Image.BILINEAR,\n",
        "    )\n",
        "    return transform\n",
        "\n",
        "def get_transform_image(cfg, is_train):\n",
        "    train_transform = cfg.train_transform\n",
        "    if train_transform == 'vitp':\n",
        "        transform = get_transform_vit_default(\n",
        "            cfg, is_train=is_train)\n",
        "    else:\n",
        "        raise NotImplementedError(train_transform)\n",
        "    return transform\n",
        "\n",
        "class ImageTransform2Images(object):\n",
        "    def __init__(self, sep_transform, first_joint=None):\n",
        "        self.image_transform = sep_transform\n",
        "        self.first_joint = first_joint\n",
        "\n",
        "    def __call__(self, imgs):\n",
        "        if self.first_joint is not None:\n",
        "            imgs = self.first_joint(imgs)\n",
        "        return [self.image_transform(im) for im in imgs]\n",
        "\n",
        "    def __repr__(self):\n",
        "        return 'ImageTransform2Images(image_transform={})'.format(\n",
        "            self.image_transform,\n",
        "        )\n",
        "\n",
        "def get_transform_images(cfg, is_train):\n",
        "    trans = get_transform_image(cfg, is_train)\n",
        "    trans = ImageTransform2Images(trans)\n",
        "    return trans\n",
        "\n",
        "def trans_select_for_crop_size(\n",
        "    data, train_crop_sizes,\n",
        "    iteration_multi=0,\n",
        "):\n",
        "    if iteration_multi <= 0:\n",
        "        if len(train_crop_sizes) == 1:\n",
        "            idx = 0\n",
        "        else:\n",
        "            idx = data['iteration'] % len(train_crop_sizes)\n",
        "    elif data['iteration'] <= iteration_multi:\n",
        "        idx = data['iteration'] % len(train_crop_sizes)\n",
        "    else:\n",
        "        idx = -1\n",
        "    return idx\n",
        "\n",
        "def get_multi_scale_image_transform(cfg, is_train, get_one=get_transform_image):\n",
        "    def get_multi_res_transform(s):\n",
        "        old = cfg.train_crop_size if is_train else cfg.test_crop_size\n",
        "        all_t = []\n",
        "        multi_res_factors = cfg.multi_res_factors or []\n",
        "        for i, f in enumerate(multi_res_factors):\n",
        "            if is_train:\n",
        "                cfg.train_crop_size = s // f\n",
        "            else:\n",
        "                cfg.test_crop_size = s // f\n",
        "            key = 'image_{}'.format(i)\n",
        "            all_t.append(RenameKey({'image': key}, not_delete_origin=True))\n",
        "            t = get_one(cfg, is_train)\n",
        "            t = ImageTransform2Dict(t, key=key)\n",
        "            all_t.append(t)\n",
        "        # get_one depends on train_crop_size\n",
        "        if is_train:\n",
        "            cfg.train_crop_size = s\n",
        "        else:\n",
        "            cfg.test_crop_size = s\n",
        "        t = get_one(cfg, is_train)\n",
        "        t = ImageTransform2Dict(t)\n",
        "        all_t.append(t)\n",
        "        if is_train:\n",
        "            cfg.train_crop_size = old\n",
        "        else:\n",
        "            cfg.test_crop_size = old\n",
        "        return transforms.Compose(all_t)\n",
        "\n",
        "    if is_train:\n",
        "        if cfg.min_size_range32 is None:\n",
        "            train_crop_sizes = [cfg.train_crop_size]\n",
        "        else:\n",
        "            train_crop_sizes = list(range(\n",
        "                cfg.min_size_range32[0],\n",
        "                cfg.min_size_range32[1] + cfg.patch_size - 1, cfg.patch_size,\n",
        "            ))\n",
        "    else:\n",
        "        train_crop_sizes = [cfg.test_crop_size]\n",
        "\n",
        "    crop_trans = []\n",
        "    for s in train_crop_sizes:\n",
        "        t = get_multi_res_transform(s)\n",
        "        crop_trans.append(t)\n",
        "    iteration_multi = 0\n",
        "    image_transform = SelectTransform(\n",
        "        crop_trans,\n",
        "        lambda d: trans_select_for_crop_size(\n",
        "            d, train_crop_sizes, iteration_multi))\n",
        "    return image_transform\n",
        "\n",
        "def forward_backward_example(image_files, captions, prefixs=None):\n",
        "    if prefixs is None:\n",
        "        prefixs = [''] * len(captions)\n",
        "    cfg = {\n",
        "        'crop_region_extend_in_datatransform': 4,\n",
        "        'data_normalize': 'clip',\n",
        "        'train_crop_size': 224,\n",
        "        'input_small_scale': 0.8,\n",
        "        'no_color_jitter': True,\n",
        "        'no_flip': True,\n",
        "        'no_aspect_dist': True,\n",
        "        'interpolation': 'bicubic',\n",
        "        'min_size_range32': [160, 224],\n",
        "        'patch_size': 16,\n",
        "        'train_transform': 'vitp',\n",
        "    }\n",
        "    cfg = Config(cfg, {})\n",
        "    all_data = []\n",
        "    tokenizer = BertTokenizer.from_pretrained('bert-base-uncased', do_lower_case=True)\n",
        "    image_transform = get_image_transform(cfg)\n",
        "    for image_file, prefix, target in zip(image_files, prefixs, captions):\n",
        "        data = get_data(image_file, prefix, target,\n",
        "                        tokenizer, image_transform)\n",
        "        all_data.append(data)\n",
        "    data = collate_fn(all_data)\n",
        "    logging.info(image_transform)\n",
        "    data = recursive_to_device(data, 'cuda')\n",
        "\n",
        "    param = {}\n",
        "    model = get_git_model(tokenizer, param)\n",
        "    model.train()\n",
        "    model.cuda()\n",
        "    loss_dict = model(data)\n",
        "    loss = sum(loss_dict.values())\n",
        "    loss.backward()\n",
        "    logging.info(loss)\n",
        "\n",
        "def speed_test_forward_backward():\n",
        "    duplicate = 32\n",
        "    image_files = ['aux_data/images/1.jpg', 'aux_data/images/2.jpg'] * duplicate\n",
        "    captions = ['a couple of boats in a large body of water.', 'a view of a mountain with a tree'] * duplicate\n",
        "\n",
        "    prefixs = [''] * len(captions)\n",
        "    cfg = {\n",
        "        'crop_region_extend_in_datatransform': 4,\n",
        "        'data_normalize': 'clip',\n",
        "        'train_crop_size': 224,\n",
        "        'input_small_scale': 0.8,\n",
        "        'no_color_jitter': True,\n",
        "        'no_flip': True,\n",
        "        'no_aspect_dist': True,\n",
        "        'interpolation': 'bicubic',\n",
        "        'min_size_range32': [160, 224],\n",
        "        'patch_size': 16,\n",
        "        'train_transform': 'vitp',\n",
        "    }\n",
        "    cfg = Config(cfg, {})\n",
        "    all_data = []\n",
        "    tokenizer = BertTokenizer.from_pretrained('bert-base-uncased', do_lower_case=True)\n",
        "    image_transform = get_image_transform(cfg)\n",
        "    for image_file, prefix, target in zip(image_files, prefixs, captions):\n",
        "        data = get_data(image_file, prefix, target,\n",
        "                        tokenizer, image_transform)\n",
        "        all_data.append(data)\n",
        "    data = collate_fn(all_data)\n",
        "    logging.info(image_transform)\n",
        "    data = recursive_to_device(data, 'cuda')\n",
        "    data['image'] = data['image'].to(torch.float16)\n",
        "\n",
        "    param = {}\n",
        "    model = get_git_model(tokenizer, param)\n",
        "    model.train()\n",
        "    model.cuda()\n",
        "    model.half()\n",
        "\n",
        "    # warmup\n",
        "    for _ in range(2):\n",
        "        loss_dict = model(data)\n",
        "        loss = sum(loss_dict.values())\n",
        "        loss.backward()\n",
        "\n",
        "    import time\n",
        "    start = time.time()\n",
        "    for iteration in range(50000):\n",
        "        loss_dict = model(data)\n",
        "        loss = sum(loss_dict.values())\n",
        "        loss.backward()\n",
        "        if (iteration % 10) == 0:\n",
        "            end = time.time()\n",
        "            speed = data['image'].shape[0] * 100 / (end - start)\n",
        "            if iteration > 0:\n",
        "                logging.info('speed = {}'.format(speed))\n",
        "            start = time.time()\n",
        "\n",
        "    logging.info(loss)\n",
        "\n",
        "\n",
        "if __name__ == '__main__':\n",
        "    init_logging()\n",
        "    kwargs = parse_general_args()\n",
        "    logging.info('param:\\n{}'.format(pformat(kwargs)))\n",
        "    function_name = kwargs['type']\n",
        "    del kwargs['type']\n",
        "    locals()[function_name](**kwargs)"
      ],
      "metadata": {
        "id": "5jiPKVCm7fHi"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "# single image, captioning\n",
        "!AZFUSE_TSV_USE_FUSE=1 python -m generativeimage2text.inference -p \"{'type': 'test_git_inference_single_image', \\\n",
        "      'image_path': 'aux_data/images/1.jpg', \\\n",
        "      'model_name': 'GIT_BASE', \\\n",
        "      'prefix': '', \\\n",
        "}\"\n",
        "# single image, question answering\n",
        "!AZFUSE_TSV_USE_FUSE=1 python -m generativeimage2text.inference -p \"{'type': 'test_git_inference_single_image', \\\n",
        "      'image_path': 'aux_data/images/1.jpg', \\\n",
        "      'model_name': 'GIT_BASE_VQAv2', \\\n",
        "      'prefix': 'what is it?', \\\n",
        "}\"\n",
        "# multiple images, captioning\n",
        "!AZFUSE_TSV_USE_FUSE=1 python -m generativeimage2text.inference -p \"{'type': 'test_git_inference_single_image', \\\n",
        "      'image_path': ['aux_data/images/1.jpg', 'aux_data/images/1.jpg', 'aux_data/images/1.jpg', 'aux_data/images/1.jpg', 'aux_data/images/1.jpg', 'aux_data/images/1.jpg'], \\\n",
        "      'model_name': 'GIT_BASE_VATEX', \\\n",
        "      'prefix': '', \\\n",
        "}\"\n",
        "# multiple images, question answering\n",
        "!AZFUSE_TSV_USE_FUSE=1 python -m generativeimage2text.inference -p \"{'type': 'test_git_inference_single_image', \\\n",
        "      'image_path': ['aux_data/images/1.jpg', 'aux_data/images/1.jpg', 'aux_data/images/1.jpg', 'aux_data/images/1.jpg', 'aux_data/images/1.jpg', 'aux_data/images/1.jpg'], \\\n",
        "      'model_name': 'GIT_BASE_MSRVTT_QA', \\\n",
        "      'prefix': 'what is it?', \\\n",
        "}\""
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "5RCkApMEVoyY",
        "outputId": "b0b6872d-5879-4ae1-bcd1-dff19ff3a8a2"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "2024-02-25 12:56:52,618.618 7181:inference.py:318   <module>(): param:\n",
            "{'image_path': 'aux_data/images/1.jpg',\n",
            " 'model_name': 'GIT_BASE',\n",
            " 'prefix': '',\n",
            " 'type': 'test_git_inference_single_image'}\n",
            "2024-02-25 12:56:57,744.744 7181:cloud_storage.py:1150 az_download_once(): if sync, no need to save to temp first\n",
            "2024-02-25 12:56:57,745.745 7181:common.py:324    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE/snapshot/model.pt /tmp/publicgit/output/GIT_BASE/snapshot/model.pt\n",
            "2024-02-25 12:56:57,746.746 7181:cloud_storage.py:1211 az_download_once(): ['azcopy',\n",
            " 'cp',\n",
            " 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE/snapshot/model.pt',\n",
            " '/tmp/publicgit/output/GIT_BASE/snapshot/model.pt']\n",
            "2024-02-25 12:56:57,746.746 7181:common.py:234 limited_retry_agent(): fails with \n",
            "[Errno 2] No such file or directory: 'azcopy': tried 1/5-th time\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "2024-02-25 12:57:01,632.632 7181:cloud_storage.py:1150 az_download_once(): if sync, no need to save to temp first\n",
            "2024-02-25 12:57:01,633.633 7181:common.py:324    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE/snapshot/model.pt /tmp/publicgit/output/GIT_BASE/snapshot/model.pt\n",
            "2024-02-25 12:57:01,634.634 7181:cloud_storage.py:1211 az_download_once(): ['azcopy',\n",
            " 'cp',\n",
            " 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE/snapshot/model.pt',\n",
            " '/tmp/publicgit/output/GIT_BASE/snapshot/model.pt']\n",
            "2024-02-25 12:57:01,634.634 7181:common.py:234 limited_retry_agent(): fails with \n",
            "[Errno 2] No such file or directory: 'azcopy': tried 2/5-th time\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "2024-02-25 12:57:05,715.715 7181:cloud_storage.py:1150 az_download_once(): if sync, no need to save to temp first\n",
            "2024-02-25 12:57:05,715.715 7181:common.py:324    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE/snapshot/model.pt /tmp/publicgit/output/GIT_BASE/snapshot/model.pt\n",
            "2024-02-25 12:57:05,716.716 7181:cloud_storage.py:1211 az_download_once(): ['azcopy',\n",
            " 'cp',\n",
            " 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE/snapshot/model.pt',\n",
            " '/tmp/publicgit/output/GIT_BASE/snapshot/model.pt']\n",
            "2024-02-25 12:57:05,716.716 7181:common.py:234 limited_retry_agent(): fails with \n",
            "[Errno 2] No such file or directory: 'azcopy': tried 3/5-th time\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "2024-02-25 12:57:10,580.580 7181:cloud_storage.py:1150 az_download_once(): if sync, no need to save to temp first\n",
            "2024-02-25 12:57:10,580.580 7181:common.py:324    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE/snapshot/model.pt /tmp/publicgit/output/GIT_BASE/snapshot/model.pt\n",
            "2024-02-25 12:57:10,582.582 7181:cloud_storage.py:1211 az_download_once(): ['azcopy',\n",
            " 'cp',\n",
            " 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE/snapshot/model.pt',\n",
            " '/tmp/publicgit/output/GIT_BASE/snapshot/model.pt']\n",
            "2024-02-25 12:57:10,582.582 7181:common.py:234 limited_retry_agent(): fails with \n",
            "[Errno 2] No such file or directory: 'azcopy': tried 4/5-th time\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "2024-02-25 12:57:11,649.649 7181:cloud_storage.py:1150 az_download_once(): if sync, no need to save to temp first\n",
            "2024-02-25 12:57:11,649.649 7181:common.py:324    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE/snapshot/model.pt /tmp/publicgit/output/GIT_BASE/snapshot/model.pt\n",
            "2024-02-25 12:57:11,650.650 7181:cloud_storage.py:1211 az_download_once(): ['azcopy',\n",
            " 'cp',\n",
            " 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE/snapshot/model.pt',\n",
            " '/tmp/publicgit/output/GIT_BASE/snapshot/model.pt']\n",
            "2024-02-25 12:57:11,650.650 7181:common.py:234 limited_retry_agent(): fails with \n",
            "[Errno 2] No such file or directory: 'azcopy': tried 5/5-th time\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"/content/GenerativeImage2Text/generativeimage2text/inference.py\", line 321, in <module>\n",
            "    locals()[function_name](**kwargs)\n",
            "  File \"/content/GenerativeImage2Text/generativeimage2text/inference.py\", line 85, in test_git_inference_single_image\n",
            "    checkpoint = torch_load(pretrained)['model']\n",
            "  File \"/content/GenerativeImage2Text/generativeimage2text/torch_common.py\", line 42, in torch_load\n",
            "    with File.open(filename, 'rb') as fp:\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/azfuse.py\", line 50, in open\n",
            "    return cls.fuser.open(fname, mode)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 497, in open\n",
            "    return self.open_to_read(info, mode)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 537, in open_to_read\n",
            "    self.ensure_remote_to_cache(remote_file, cache_file, cloud,\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 644, in ensure_remote_to_cache\n",
            "    self.remote_to_cache(remote_file, cache_file, cloud, cache_lock)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 616, in remote_to_cache\n",
            "    cloud.az_download(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1130, in az_download\n",
            "    limited_retry_agent(retry, self.az_download_once,\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "2024-02-25 12:57:15,609.609 7285:inference.py:318   <module>(): param:\n",
            "{'image_path': 'aux_data/images/1.jpg',\n",
            " 'model_name': 'GIT_BASE_VQAv2',\n",
            " 'prefix': 'what is it?',\n",
            " 'type': 'test_git_inference_single_image'}\n",
            "2024-02-25 12:57:20,770.770 7285:cloud_storage.py:1150 az_download_once(): if sync, no need to save to temp first\n",
            "2024-02-25 12:57:20,770.770 7285:common.py:324    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE_VQAv2/snapshot/model.pt /tmp/publicgit/output/GIT_BASE_VQAv2/snapshot/model.pt\n",
            "2024-02-25 12:57:20,772.772 7285:cloud_storage.py:1211 az_download_once(): ['azcopy',\n",
            " 'cp',\n",
            " 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE_VQAv2/snapshot/model.pt',\n",
            " '/tmp/publicgit/output/GIT_BASE_VQAv2/snapshot/model.pt']\n",
            "2024-02-25 12:57:20,772.772 7285:common.py:234 limited_retry_agent(): fails with \n",
            "[Errno 2] No such file or directory: 'azcopy': tried 1/5-th time\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "2024-02-25 12:57:24,329.329 7285:cloud_storage.py:1150 az_download_once(): if sync, no need to save to temp first\n",
            "2024-02-25 12:57:24,329.329 7285:common.py:324    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE_VQAv2/snapshot/model.pt /tmp/publicgit/output/GIT_BASE_VQAv2/snapshot/model.pt\n",
            "2024-02-25 12:57:24,330.330 7285:cloud_storage.py:1211 az_download_once(): ['azcopy',\n",
            " 'cp',\n",
            " 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE_VQAv2/snapshot/model.pt',\n",
            " '/tmp/publicgit/output/GIT_BASE_VQAv2/snapshot/model.pt']\n",
            "2024-02-25 12:57:24,330.330 7285:common.py:234 limited_retry_agent(): fails with \n",
            "[Errno 2] No such file or directory: 'azcopy': tried 2/5-th time\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "2024-02-25 12:57:27,756.756 7285:cloud_storage.py:1150 az_download_once(): if sync, no need to save to temp first\n",
            "2024-02-25 12:57:27,756.756 7285:common.py:324    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE_VQAv2/snapshot/model.pt /tmp/publicgit/output/GIT_BASE_VQAv2/snapshot/model.pt\n",
            "2024-02-25 12:57:27,758.758 7285:cloud_storage.py:1211 az_download_once(): ['azcopy',\n",
            " 'cp',\n",
            " 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE_VQAv2/snapshot/model.pt',\n",
            " '/tmp/publicgit/output/GIT_BASE_VQAv2/snapshot/model.pt']\n",
            "2024-02-25 12:57:27,758.758 7285:common.py:234 limited_retry_agent(): fails with \n",
            "[Errno 2] No such file or directory: 'azcopy': tried 3/5-th time\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "2024-02-25 12:57:30,415.415 7285:cloud_storage.py:1150 az_download_once(): if sync, no need to save to temp first\n",
            "2024-02-25 12:57:30,416.416 7285:common.py:324    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE_VQAv2/snapshot/model.pt /tmp/publicgit/output/GIT_BASE_VQAv2/snapshot/model.pt\n",
            "2024-02-25 12:57:30,417.417 7285:cloud_storage.py:1211 az_download_once(): ['azcopy',\n",
            " 'cp',\n",
            " 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE_VQAv2/snapshot/model.pt',\n",
            " '/tmp/publicgit/output/GIT_BASE_VQAv2/snapshot/model.pt']\n",
            "2024-02-25 12:57:30,417.417 7285:common.py:234 limited_retry_agent(): fails with \n",
            "[Errno 2] No such file or directory: 'azcopy': tried 4/5-th time\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "2024-02-25 12:57:32,745.745 7285:cloud_storage.py:1150 az_download_once(): if sync, no need to save to temp first\n",
            "2024-02-25 12:57:32,745.745 7285:common.py:324    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE_VQAv2/snapshot/model.pt /tmp/publicgit/output/GIT_BASE_VQAv2/snapshot/model.pt\n",
            "2024-02-25 12:57:32,746.746 7285:cloud_storage.py:1211 az_download_once(): ['azcopy',\n",
            " 'cp',\n",
            " 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE_VQAv2/snapshot/model.pt',\n",
            " '/tmp/publicgit/output/GIT_BASE_VQAv2/snapshot/model.pt']\n",
            "2024-02-25 12:57:32,746.746 7285:common.py:234 limited_retry_agent(): fails with \n",
            "[Errno 2] No such file or directory: 'azcopy': tried 5/5-th time\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"/content/GenerativeImage2Text/generativeimage2text/inference.py\", line 321, in <module>\n",
            "    locals()[function_name](**kwargs)\n",
            "  File \"/content/GenerativeImage2Text/generativeimage2text/inference.py\", line 85, in test_git_inference_single_image\n",
            "    checkpoint = torch_load(pretrained)['model']\n",
            "  File \"/content/GenerativeImage2Text/generativeimage2text/torch_common.py\", line 42, in torch_load\n",
            "    with File.open(filename, 'rb') as fp:\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/azfuse.py\", line 50, in open\n",
            "    return cls.fuser.open(fname, mode)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 497, in open\n",
            "    return self.open_to_read(info, mode)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 537, in open_to_read\n",
            "    self.ensure_remote_to_cache(remote_file, cache_file, cloud,\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 644, in ensure_remote_to_cache\n",
            "    self.remote_to_cache(remote_file, cache_file, cloud, cache_lock)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 616, in remote_to_cache\n",
            "    cloud.az_download(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1130, in az_download\n",
            "    limited_retry_agent(retry, self.az_download_once,\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "2024-02-25 12:57:37,091.091 7381:inference.py:318   <module>(): param:\n",
            "{'image_path': ['aux_data/images/1.jpg',\n",
            "                'aux_data/images/1.jpg',\n",
            "                'aux_data/images/1.jpg',\n",
            "                'aux_data/images/1.jpg',\n",
            "                'aux_data/images/1.jpg',\n",
            "                'aux_data/images/1.jpg'],\n",
            " 'model_name': 'GIT_BASE_VATEX',\n",
            " 'prefix': '',\n",
            " 'type': 'test_git_inference_single_image'}\n",
            "2024-02-25 12:57:41,719.719 7381:decoder.py:832   __init__(): creating temperal embedding\n",
            "2024-02-25 12:57:42,269.269 7381:cloud_storage.py:1150 az_download_once(): if sync, no need to save to temp first\n",
            "2024-02-25 12:57:42,270.270 7381:common.py:324    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE_VATEX/snapshot/model.pt /tmp/publicgit/output/GIT_BASE_VATEX/snapshot/model.pt\n",
            "2024-02-25 12:57:42,271.271 7381:cloud_storage.py:1211 az_download_once(): ['azcopy',\n",
            " 'cp',\n",
            " 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE_VATEX/snapshot/model.pt',\n",
            " '/tmp/publicgit/output/GIT_BASE_VATEX/snapshot/model.pt']\n",
            "2024-02-25 12:57:42,271.271 7381:common.py:234 limited_retry_agent(): fails with \n",
            "[Errno 2] No such file or directory: 'azcopy': tried 1/5-th time\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "2024-02-25 12:57:44,772.772 7381:cloud_storage.py:1150 az_download_once(): if sync, no need to save to temp first\n",
            "2024-02-25 12:57:44,773.773 7381:common.py:324    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE_VATEX/snapshot/model.pt /tmp/publicgit/output/GIT_BASE_VATEX/snapshot/model.pt\n",
            "2024-02-25 12:57:44,774.774 7381:cloud_storage.py:1211 az_download_once(): ['azcopy',\n",
            " 'cp',\n",
            " 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE_VATEX/snapshot/model.pt',\n",
            " '/tmp/publicgit/output/GIT_BASE_VATEX/snapshot/model.pt']\n",
            "2024-02-25 12:57:44,774.774 7381:common.py:234 limited_retry_agent(): fails with \n",
            "[Errno 2] No such file or directory: 'azcopy': tried 2/5-th time\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "2024-02-25 12:57:49,757.757 7381:cloud_storage.py:1150 az_download_once(): if sync, no need to save to temp first\n",
            "2024-02-25 12:57:49,757.757 7381:common.py:324    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE_VATEX/snapshot/model.pt /tmp/publicgit/output/GIT_BASE_VATEX/snapshot/model.pt\n",
            "2024-02-25 12:57:49,758.758 7381:cloud_storage.py:1211 az_download_once(): ['azcopy',\n",
            " 'cp',\n",
            " 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE_VATEX/snapshot/model.pt',\n",
            " '/tmp/publicgit/output/GIT_BASE_VATEX/snapshot/model.pt']\n",
            "2024-02-25 12:57:49,758.758 7381:common.py:234 limited_retry_agent(): fails with \n",
            "[Errno 2] No such file or directory: 'azcopy': tried 3/5-th time\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "2024-02-25 12:57:50,904.904 7381:cloud_storage.py:1150 az_download_once(): if sync, no need to save to temp first\n",
            "2024-02-25 12:57:50,904.904 7381:common.py:324    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE_VATEX/snapshot/model.pt /tmp/publicgit/output/GIT_BASE_VATEX/snapshot/model.pt\n",
            "2024-02-25 12:57:50,905.905 7381:cloud_storage.py:1211 az_download_once(): ['azcopy',\n",
            " 'cp',\n",
            " 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE_VATEX/snapshot/model.pt',\n",
            " '/tmp/publicgit/output/GIT_BASE_VATEX/snapshot/model.pt']\n",
            "2024-02-25 12:57:50,905.905 7381:common.py:234 limited_retry_agent(): fails with \n",
            "[Errno 2] No such file or directory: 'azcopy': tried 4/5-th time\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "2024-02-25 12:57:54,135.135 7381:cloud_storage.py:1150 az_download_once(): if sync, no need to save to temp first\n",
            "2024-02-25 12:57:54,136.136 7381:common.py:324    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE_VATEX/snapshot/model.pt /tmp/publicgit/output/GIT_BASE_VATEX/snapshot/model.pt\n",
            "2024-02-25 12:57:54,137.137 7381:cloud_storage.py:1211 az_download_once(): ['azcopy',\n",
            " 'cp',\n",
            " 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE_VATEX/snapshot/model.pt',\n",
            " '/tmp/publicgit/output/GIT_BASE_VATEX/snapshot/model.pt']\n",
            "2024-02-25 12:57:54,137.137 7381:common.py:234 limited_retry_agent(): fails with \n",
            "[Errno 2] No such file or directory: 'azcopy': tried 5/5-th time\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"/content/GenerativeImage2Text/generativeimage2text/inference.py\", line 321, in <module>\n",
            "    locals()[function_name](**kwargs)\n",
            "  File \"/content/GenerativeImage2Text/generativeimage2text/inference.py\", line 85, in test_git_inference_single_image\n",
            "    checkpoint = torch_load(pretrained)['model']\n",
            "  File \"/content/GenerativeImage2Text/generativeimage2text/torch_common.py\", line 42, in torch_load\n",
            "    with File.open(filename, 'rb') as fp:\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/azfuse.py\", line 50, in open\n",
            "    return cls.fuser.open(fname, mode)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 497, in open\n",
            "    return self.open_to_read(info, mode)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 537, in open_to_read\n",
            "    self.ensure_remote_to_cache(remote_file, cache_file, cloud,\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 644, in ensure_remote_to_cache\n",
            "    self.remote_to_cache(remote_file, cache_file, cloud, cache_lock)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 616, in remote_to_cache\n",
            "    cloud.az_download(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1130, in az_download\n",
            "    limited_retry_agent(retry, self.az_download_once,\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "2024-02-25 12:57:58,721.721 7477:inference.py:318   <module>(): param:\n",
            "{'image_path': ['aux_data/images/1.jpg',\n",
            "                'aux_data/images/1.jpg',\n",
            "                'aux_data/images/1.jpg',\n",
            "                'aux_data/images/1.jpg',\n",
            "                'aux_data/images/1.jpg',\n",
            "                'aux_data/images/1.jpg'],\n",
            " 'model_name': 'GIT_BASE_MSRVTT_QA',\n",
            " 'prefix': 'what is it?',\n",
            " 'type': 'test_git_inference_single_image'}\n",
            "2024-02-25 12:58:03,350.350 7477:decoder.py:832   __init__(): creating temperal embedding\n",
            "2024-02-25 12:58:03,896.896 7477:cloud_storage.py:1150 az_download_once(): if sync, no need to save to temp first\n",
            "2024-02-25 12:58:03,897.897 7477:common.py:324    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE_MSRVTT_QA/snapshot/model.pt /tmp/publicgit/output/GIT_BASE_MSRVTT_QA/snapshot/model.pt\n",
            "2024-02-25 12:58:03,898.898 7477:cloud_storage.py:1211 az_download_once(): ['azcopy',\n",
            " 'cp',\n",
            " 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE_MSRVTT_QA/snapshot/model.pt',\n",
            " '/tmp/publicgit/output/GIT_BASE_MSRVTT_QA/snapshot/model.pt']\n",
            "2024-02-25 12:58:03,898.898 7477:common.py:234 limited_retry_agent(): fails with \n",
            "[Errno 2] No such file or directory: 'azcopy': tried 1/5-th time\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "2024-02-25 12:58:04,700.700 7477:cloud_storage.py:1150 az_download_once(): if sync, no need to save to temp first\n",
            "2024-02-25 12:58:04,701.701 7477:common.py:324    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE_MSRVTT_QA/snapshot/model.pt /tmp/publicgit/output/GIT_BASE_MSRVTT_QA/snapshot/model.pt\n",
            "2024-02-25 12:58:04,702.702 7477:cloud_storage.py:1211 az_download_once(): ['azcopy',\n",
            " 'cp',\n",
            " 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE_MSRVTT_QA/snapshot/model.pt',\n",
            " '/tmp/publicgit/output/GIT_BASE_MSRVTT_QA/snapshot/model.pt']\n",
            "2024-02-25 12:58:04,702.702 7477:common.py:234 limited_retry_agent(): fails with \n",
            "[Errno 2] No such file or directory: 'azcopy': tried 2/5-th time\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "2024-02-25 12:58:07,058.058 7477:cloud_storage.py:1150 az_download_once(): if sync, no need to save to temp first\n",
            "2024-02-25 12:58:07,058.058 7477:common.py:324    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE_MSRVTT_QA/snapshot/model.pt /tmp/publicgit/output/GIT_BASE_MSRVTT_QA/snapshot/model.pt\n",
            "2024-02-25 12:58:07,059.059 7477:cloud_storage.py:1211 az_download_once(): ['azcopy',\n",
            " 'cp',\n",
            " 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE_MSRVTT_QA/snapshot/model.pt',\n",
            " '/tmp/publicgit/output/GIT_BASE_MSRVTT_QA/snapshot/model.pt']\n",
            "2024-02-25 12:58:07,060.060 7477:common.py:234 limited_retry_agent(): fails with \n",
            "[Errno 2] No such file or directory: 'azcopy': tried 3/5-th time\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "2024-02-25 12:58:09,663.663 7477:cloud_storage.py:1150 az_download_once(): if sync, no need to save to temp first\n",
            "2024-02-25 12:58:09,663.663 7477:common.py:324    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE_MSRVTT_QA/snapshot/model.pt /tmp/publicgit/output/GIT_BASE_MSRVTT_QA/snapshot/model.pt\n",
            "2024-02-25 12:58:09,665.665 7477:cloud_storage.py:1211 az_download_once(): ['azcopy',\n",
            " 'cp',\n",
            " 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE_MSRVTT_QA/snapshot/model.pt',\n",
            " '/tmp/publicgit/output/GIT_BASE_MSRVTT_QA/snapshot/model.pt']\n",
            "2024-02-25 12:58:09,665.665 7477:common.py:234 limited_retry_agent(): fails with \n",
            "[Errno 2] No such file or directory: 'azcopy': tried 4/5-th time\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "2024-02-25 12:58:13,695.695 7477:cloud_storage.py:1150 az_download_once(): if sync, no need to save to temp first\n",
            "2024-02-25 12:58:13,695.695 7477:common.py:324    cmd_run(): start to cmd run: azcopy cp https://publicgit.blob.core.windows.net/data/output/GIT_BASE_MSRVTT_QA/snapshot/model.pt /tmp/publicgit/output/GIT_BASE_MSRVTT_QA/snapshot/model.pt\n",
            "2024-02-25 12:58:13,696.696 7477:cloud_storage.py:1211 az_download_once(): ['azcopy',\n",
            " 'cp',\n",
            " 'https://publicgit.blob.core.windows.net/data/output/GIT_BASE_MSRVTT_QA/snapshot/model.pt',\n",
            " '/tmp/publicgit/output/GIT_BASE_MSRVTT_QA/snapshot/model.pt']\n",
            "2024-02-25 12:58:13,696.696 7477:common.py:234 limited_retry_agent(): fails with \n",
            "[Errno 2] No such file or directory: 'azcopy': tried 5/5-th time\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"/content/GenerativeImage2Text/generativeimage2text/inference.py\", line 321, in <module>\n",
            "    locals()[function_name](**kwargs)\n",
            "  File \"/content/GenerativeImage2Text/generativeimage2text/inference.py\", line 85, in test_git_inference_single_image\n",
            "    checkpoint = torch_load(pretrained)['model']\n",
            "  File \"/content/GenerativeImage2Text/generativeimage2text/torch_common.py\", line 42, in torch_load\n",
            "    with File.open(filename, 'rb') as fp:\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/azfuse.py\", line 50, in open\n",
            "    return cls.fuser.open(fname, mode)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 497, in open\n",
            "    return self.open_to_read(info, mode)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 537, in open_to_read\n",
            "    self.ensure_remote_to_cache(remote_file, cache_file, cloud,\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 644, in ensure_remote_to_cache\n",
            "    self.remote_to_cache(remote_file, cache_file, cloud, cache_lock)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 616, in remote_to_cache\n",
            "    cloud.az_download(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1130, in az_download\n",
            "    limited_retry_agent(retry, self.az_download_once,\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 232, in limited_retry_agent\n",
            "    return func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/cloud_storage.py\", line 1209, in az_download_once\n",
            "    cmd_run(cmd, stdout=stdout)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/azfuse/common.py\", line 345, in cmd_run\n",
            "    p = sp.Popen(' '.join(list_cmd) if shell else list_cmd,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 971, in __init__\n",
            "    self._execute_child(args, executable, preexec_fn, close_fds,\n",
            "  File \"/usr/lib/python3.10/subprocess.py\", line 1863, in _execute_child\n",
            "    raise child_exception_type(errno_num, err_msg, err_filename)\n",
            "FileNotFoundError: [Errno 2] No such file or directory: 'azcopy'\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "1bG1PkhuVuYq"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}